### ISSUE TITLE
Endpoint Guide

### ISSUE THREAD

**Issue by lancehalvorsen** [phoenixframework/phoenix_guides#124]
We certainly need one.

**Comment by gjaldon** [comment]
I'd like to help out with this too, @lancehalvorsen. Just let me know which one you prefer I take on.

**Comment by lancehalvorsen** [comment]
Thanks for this as well, @gjaldon! Much appreciated.

This guide would be fine to work on, if it interests you. A Heroku deployment guide would be great as well. This would be a new file.

**Comment by willykaram** [comment]
@gjaldon @lancehalvorsen I just wanted to check on the status of the Endpoint Guide. It looks like the Heroku Deployment Guide is done, but we didn't tackle the endpoint guide yet. I can create a proposed draft this week if helpful, but don't want to duplicate any other work if others or @gjaldon are already working on it.

**Comment by lancehalvorsen** [comment]
As far as I know, nobody is currently working on this. It would be fabulous if you wanted to take this on @willykaram!

**Comment by dmitrinesterenko** [comment]
I'm taking this one on.

**Comment by willykaram** [comment]
@dmitrinesterenko thx, that would rock!! As discussed, ideally we can incorporate some of that into the the diagram for #118 and an accompanying guide.

**Comment by dmitrinesterenko** [comment]
What would be the appropriate name for this guide? I.e. C_controllers. E_endpoints? There is an implied order in the selection of the title letters and I'm interested in where the endpoints would fall.

**Comment by willykaram** [comment]
@dmitrinesterenko I wasn't sure of which letter to use for the naming either, so for this issue #365 & related PR #465 I just used "X" as the alpha prefix. That could likely work for now, and then @lancehalvorsen for @jeregrine could rename it appropriately.

If there's a clear strategy/approach for the naming, then  perhaps we could update the [Contributing to the Phoenix Guides](https://github.com/phoenixframework/phoenix_guides/blob/master/CONTRIBUTING.md) and the root READ.me file

**Comment by jeregrine** [comment]
I think the numbers are sort of an informal ordering, I wasn't around for there creation.

**Comment by xuebingli** [comment]
@dmitrinesterenko has created the guide https://github.com/phoenixframework/phoenix_guides/pull/567

**Comment by chrismccord** [comment]
We can work the endpoint discussion when talking about routing and the plug pipeline
