### ISSUE TITLE
Deployment with ecto

### ISSUE THREAD

**Issue by shankardevy** [phoenixframework/phoenix_guides#155]
http://www.phoenixframework.org/v0.10.0/docs/advanced-deployment describes deployment to server by copying a tar file to server, extracting and running the start script. However, it does not give any information about the following

1. How are the database credentials on the prod server passed to app.
2. Does exrm release take care of any migration related tasks.
3. When v0.1 is deployed and it needs to be updated new version v.2, how does one update the live site with the new migrations?

**Comment by lancehalvorsen** [comment]
@shankardevy those are great questions! I don't currently know the answers to them! :)

If you were interested in finding the answers, I would totally love a PR. Otherwise, I will get to them, but other things will take precedence.

**Comment by gjaldon** [comment]
@shankardevy below are some answers to the questions you posted in case you haven't yet solved them:
> 1. How are the database credentials on the prod server passed to app. 

I'm not sure what you mean here. Ideally, the database credentials for your prod server wouldn't be stored in your app's git repo. You will need to manually configure your Phoenix app's Ecto DB for your prod server.
To set the DB credentials for your app in production, you will need both `config/prod.secret.exs` file where you can configure your DB like:
```elixir
config :chiron, Chiron.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: "postgres",
  password: "postgres",
  database: "chiron_prod",
  size: 20 # The amount of database connections in the pool
```

> 2. Does exrm release take care of any migration related tasks.

No, you will need to run the migrations after deploying. You could automate this via git's post-receive hook or through whatever deployment tool you may use.

> 3. When v0.1 is deployed and it needs to be updated new version v.2, how does one update the live site with the new migrations?

The same answer as for number 2. 

Let me know if I understood your questions correctly.

**Comment by josevalim** [comment]
I am closing this because I have discussed most of them in the introduction to deployment guide. We may still need to improve the EXRM guides in some ports so PRs are still welcome.
