### ISSUE TITLE
URL helpers should pass the connection instead of the endpoint as much as possible

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix_guides#171]
First of all, we should likely ask users to `import MyApp.Router.Helpers` instead of always referencing it by full alias. Then, if we have a connection available (which is true in controllers, views, etc), we always pass the connection:

```
user_path(conn, :index)
```

The endpoint should only be used in contexts where the connection is not available, like mailers:

```
user_path(MyApp.Endpoint, :index)
```

**Comment by lancehalvorsen** [comment]
Valuable feedback @josevalim. Thanks!

**Comment by schnittchen** [comment]
This leaves one problem open: When phoenix runs behind a reverse proxy, mailer urls will include a broken host:port combination.

I have this issue right now... next step source diving :)

**Comment by josevalim** [comment]
@schnittchen there is a configuration in your endpoint that configures which URL want you want to generate. So if you are behind a reverse proxy, you should configure it to your actual host and port. Check your config/prod.exs and set:

```elixir
url: [host: "example.com", port: 80]
```

**Comment by schnittchen** [comment]
Thank you jose! Will try that and try to come up with a PR.

**Comment by jeregrine** [comment]
Thanks! ❤️
