### ISSUE TITLE
Group API docs

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix_guides#214]
Hello folks,

Today we at the header we link to API Docs that contains Phoenix documentation. However, I think it would also be important to link to at least Ecto and Plug docs too. Furthermore, we will extract Phoenix.HTML in the next release so I think we should link to those too. So my proposal is to have API Docs linking to a page inside readme.io with links and short descriptions to:

* Phoenix - the web framework (endpoints, router, controller, view and channels)
  * Docs
  * Source

* Phoenix.HTML - brings HTML generation functionality into your Phoenix apps
  * Docs
  * Source

* Plug - provides pipelines and the client-server connection abstraction used by Phoenix
  * Docs
  * Source

* Ecto - the model layer that ships with Phoenix
  * Docs
  * Source

* Elixir - the programming language Phoenix is built on
  * Website
  * Docs
  * Source

The goal is to link to docs the user may need. For this reason I wouldn't link to Cowboy because we never use its API directly nor EEx. We have similar things in the resources page, so I would extract those from there and move them here.

**Comment by josevalim** [comment]
I have noticed this crashes a little bit with the Overview page. Should we also add Ecto and Phoenix.HTML to overview?

**Comment by lancehalvorsen** [comment]
I believe this is now complete between these two pages:
http://www.phoenixframework.org/v0.13.1/docs/resources
http://www.phoenixframework.org/v0.13.1/docs/learning-elixir-and-erlang
