### ISSUE TITLE
Find a place for reference applications

### ISSUE THREAD

**Issue by jeffweiss** [phoenixframework/phoenix_guides#231]
I created an Elixir - Phoenix [implementation](https://github.com/jeffweiss/todobackend-phoenix/blob/master/README.md) for [Todo-Backend](http://www.todobackend.com/). Should this be an additional exercise in the guides? Should it be linked in a section for reference applications?

**Comment by lancehalvorsen** [comment]
Thanks for adding this! 

Once we get the new Phoenix release settled in, we can have a solid conversation about where these should go.

**Comment by willykaram** [comment]
@jeffweiss @jeregrine @lancehalvorsen I wonder if it would make sense to host reference applications external to the guides? I was thinking it might make sense to have a community site or wiki setup where we could list this, along with tutorials and other materials. 

I have a list of these sorts of references/examples that could be pulled together for that. A few examples:

_Trello Clone_
https://blog.diacode.com/trello-clone-with-phoenix-and-react-pt-1

_Blog Example_
https://medium.com/elixir-magic/writing-a-blog-engine-in-phoenix-and-elixir-part-9-live-comments-9269669a6941

_15 Min Blog Example_
https://www.monterail.com/blog/2015/phoenix-blog

_Changelog.com_
https://github.com/thechangelog/changelog.com

_ExAdmin Demo #1 _
https://github.com/smpallen99/ex_admin

_ExAdmin Demo #2 _
https://github.com/smpallen99/contact_demo

_Pluralsight Course App_
https://github.com/taylonr/rsvp_umbrella

_Udemy Course Apps_
https://github.com/StephenGrider/ElixirCode

This also appears to be a community example along these lines which forks existing example repos

_Multiple Examples Here_
https://github.com/phoenix-examples

**Comment by willykaram** [comment]
BTW, to be clear, I have a much longer list of these examples, but these are some representative ones.

**Comment by chrismccord** [comment]
I agree reference applications should not be part of the guides. Whatever applications we would link to for reference would need to be vetted by the guide maintainers so we need to be careful what we link to reference wise.
