### ISSUE TITLE
Add ElixirConfEU keynote to site

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix_guides#235]
Just like the ElixirConfUS talk is on the overview, we should have the new video somewhere. It could replace the ElixirConfUS video or go into a blog post or?

**Comment by josevalim** [comment]
:+1: for blog post. The news section already has a link on the menu and it has been a while since has been last updated.

**Comment by lancehalvorsen** [comment]
This is linked to in the "Learning" guide.
