### ISSUE TITLE
Lack of example apps mirroring the guides

### ISSUE THREAD

**Issue by ybur-yug** [phoenixframework/phoenix_guides#242]
Not a real 'issue', per se, but I figured this would be easier to reach out on than on IRC.

I've been going through the docs/guides and love what I see. However, there is a definite lack of current phoenix applications that can be simply referenced to see 'the right way' or standard conventions to do things. I would gladly clean up the code I have from going through the guides thus far and potentially have 1 simple folder for each section of the guides (ie a barebones generated app, generating a simple view, adding in models, etc).

So, if this is something you guys would like to have in this repository let me know and I will gladly fork+PR in the coming week or so :)

Keep up the great work!

**Comment by ybur-yug** [comment]
Here is an example of what I am speaking of specifically. My idea is to have each commit be one of the larger steps in the guide, starting from the dead beginning.
https://github.com/ybur-yug/phoenix_guides_app

**Comment by ybur-yug** [comment]
I also noticed @chrismccord has the chat app that it builds up to as a whole, but I thought it may be beneficial to have a commit-by-commit version going through the steps that build up the app (while there isn't much to show with src for things like the routing bit where its largely playing in iex etc)

Anywho, feel free to close if it doesn't sound like a good idea but otherwise let me know if you'd like me to contribute something for it :)

**Comment by chrismccord** [comment]
@ybur-yug better examples and step by step instruction are on my list of todos, but it's a long list :). We haven't had example apps yet because it's another thing for us to maintain and lots of rework when things change. Expect a better story here soon. Thanks!

**Comment by ybur-yug** [comment]
thanks @chrismccord ! 
If there is anything I can offer w.r.t documentation, my skills probably arent high enough in Elixir itself to contribute to the framework, but I'd be happy to help with docs/guides/examples if the need arises and you let me know :)
