### ISSUE TITLE
Revive the Static Asset Guide

### ISSUE THREAD

**Issue by lancehalvorsen** [phoenixframework/phoenix_guides#246]
We need to better explain the interplay between Phoenix and brunch.io.
- more info on how to control brunch installation at app generation time
- explain how to use another asset management system in Phoenix, say WebPack instead of brunch
- explain how brunch works inside of Phoenix
- talk about compiling assets for deployment

**Comment by leikind** [comment]
Please have a look at https://gist.github.com/leikind/97822f34376c908d56ee .

I know, it doesn't answer all the questions you listed, like the one about deployment or using other asset management systems, but would you consider it  as a starting point?

**Comment by leikind** [comment]
I added a section on using another asset build tool.

**Comment by paulcsmith** [comment]
@leikind That is really helpful. I think another important section would be "Working with third party libraries". Things like integrating with bower or npm, etc. There are some guides n Brunch, but the guides are *so big* it's hard to find what the recommendation is and where to look

**Comment by leikind** [comment]
my idea was to keep the guide short and to only give a certain minimum info for getting started. I believe Brunch docs are pretty good and it doesn't feel right to duplicate them. But I did list other functionalities Brunch offers, bower integration among them.

**Comment by paulcsmith** [comment]
Yeah that's a good point, but I don't think it would hurt to link to the actual page so people don't have to go look for it. What do you think?

**Comment by leikind** [comment]
I agree. I added links to the section on bower integration and split targets.

**Comment by lancehalvorsen** [comment]
Hi @leikind and @paulcsmith. You both seem to have ideas about how this guide should be structured. Either of you care to take a shot at it? A PR would be greatly appreciated!

**Comment by leikind** [comment]
@lancehalvorsen , I did write a draft version of the guide https://gist.github.com/leikind/97822f34376c908d56ee . If you find it a good starting point I can make a PR.

**Comment by lancehalvorsen** [comment]
Ah, sorry! I missed that part. I should get a chance to look at it before the end of the weekend. Thanks!

**Comment by leikind** [comment]
Allright. Then I'd better wait for your feedback

**Comment by lancehalvorsen** [comment]
Ok, I got curious and decided to ignore the thing I really should be doing and read your gist @leikind, which is awesome! :^) Please do send a PR!

I would make one general comment that you might want to consider before submitting it. We have a convention in the guides to use "we" and "our" wherever possible instead of "you" and "your". This is a subtle difference, but my hope is that it creates a tone of inclusion for all readers.

Also, @paulcsmith, if I could ask you to verify this factually on the tech side, that would be fabulous. I'm less familiar with Brunch than I probably should be.

Thank you both!

**Comment by lancehalvorsen** [comment]
Ah, and I forgot. There is a placeholder for this guide here:
https://github.com/phoenixframework/phoenix_guides/blob/master/bonus_guides/G_static_assets.md

Please use that file for your PR.

Thanks so much! <3 <3 <3

**Comment by leikind** [comment]
you → we : point taken

PR submitted
