### ISSUE TITLE
Add changes to test_helper in `upgrading from 0.11.0`

### ISSUE THREAD

**Issue by paulcsmith** [phoenixframework/phoenix_guides#260]
http://www.phoenixframework.org/v0.13.1/docs/upgrading-from-v0110 does not mention the changes to https://github.com/phoenixframework/phoenix/commit/ed0343ed94e85228a26da289d5a2520a5a93bb0c (see test_helper.exs) which are required for the new `ConnCase` helpers. Without the restart transaction function being called the database does not clear correctly between tests.

See https://github.com/phoenixframework/phoenix/issues/894

**Comment by paulcsmith** [comment]
The changes in `mix.exs` might also be needed. Otherwise the new files for `MyApp.ConnCase` won't be loaded in the test env

I can add this to readme.io if it looks good:

```
# At the bottom of the `## Test Helpers` section

3) Load your new test helpers from `test/support` in `mix.exs`

    # Change your elixirrc_paths to use this function
    elixirc_paths: elixirc_paths(Mix.env)

    # Add these functions
    # Specifies which paths to compile per environment
    defp elixirc_paths(:test), do: ["lib", "web", "test/support"]
    defp elixirc_paths(_),     do: ["lib", "web"]

4) If you're using Ecto, add this to the bottom of your `test/test_helper.exs`. Replace `MyApp` with your app name.

    # Create the database, run migrations, and start the test transaction.
    Mix.Task.run "ecto.create", ["--quiet"]
    Mix.Task.run "ecto.migrate", ["--quiet"]
    Ecto.Adapters.SQL.begin_test_transaction(MyApp.Repo)
```

**Comment by lancehalvorsen** [comment]
Would that be upgrading from 0.11.0  or 0.12.0?

**Comment by paulcsmith** [comment]
Not positive. I know that it is needed to make 0.11.0 -> 0.12.0 work. Otherwise the ConnCase helpers that it says to add will not work correctly.

**Comment by lancehalvorsen** [comment]
I'm not positive either. I'll get a chance to check this evening. If you get a chance to check before then, that would be much appreciated.

I definitely want to add this, just want to make sure it gets to the right place.

**Comment by paulcsmith** [comment]
Both the test_helper and mix.exs changes should be in the upgrade from 0.10.0 guide. Both were added in 0.11.0

The elixic_paths stuff is for the upgrade from 0.10.0 guide. It's in Chris's gist, but not in Readme.io

https://gist.github.com/chrismccord/3603fd2735019f86c74b
http://www.phoenixframework.org/v0.13.1/docs/upgrading-from-v0100

It looks like the `test_helper` stuff was also added in 0.11.0, but was not in Chris's gist or in the Readme upgrade guide.

**Comment by paulcsmith** [comment]
Might be helpful to add a note at the end of the "upgrading from Phoenix 0.11.0" guide though. Something like "Be sure to make the test_helper and mix.exs changes mention in 0.10.0 (since it was accidentally left out). Maybe that's redundant though?

**Comment by lancehalvorsen** [comment]
Thanks so much for checking, @paulcsmith. If you're still willing to update readme.io, that would be fabulous! Thanks again! <3 <3 <3

**Comment by paulcsmith** [comment]
Yep I can do that tonight or tomorrow! :D

**Comment by lancehalvorsen** [comment]
:+1:

**Comment by paulcsmith** [comment]
@lancehalvorsen I added it here: http://www.phoenixframework.org/v0.13.1/docs/upgrading-from-v0100#section-test-helpers

If it looks good I'll close this issue :)

**Comment by lancehalvorsen** [comment]
@paulcsmith Thanks so much for this!
