### ISSUE TITLE
Update Mix Tasks Guide with New Tasks

### ISSUE THREAD

**Issue by lancehalvorsen** [phoenixframework/phoenix_guides#261]
There are a number of new mix tasks which we need to document in the Mix Tasks Guide. There are also a few other tweaks to catch up with as well.

- add phoenix.gen.json
- add phoenix.gen.channel
- add phoenix.gen.model
- add phoenix.digest
- tweak phoenix.gen.html - expand explanation to include --no-model
- tweak phoenix.gen.html task to include test files generated
- replace list of phoenix tasks at the top with the following:

~/work/elixir-stuff/hello_phoenix$ mix help | grep -i phoenix
mix phoenix.digest      # Digests and compress static files
mix phoenix.gen.channel # Generates a Phoenix channel
mix phoenix.gen.html    # Generates controller, model and views for an HTML-based resource
mix phoenix.gen.json    # Generates a controller and model for an JSON-based resource
mix phoenix.gen.model   # Generates an Ecto model
mix phoenix.new         # Create a new Phoenix v0.13.1 application
mix phoenix.routes      # Prints all routes
mix phoenix.server      # Starts applications and their servers

**Comment by ugisozols** [comment]
I'd like to work on this :) (just saying to check if someone else might be working on it already).

**Comment by lancehalvorsen** [comment]
Please do!  :)

**Comment by ugisozols** [comment]
- [ ] add phoenix.gen.json
- [ ] add phoenix.gen.channel
- [ ] add phoenix.gen.model
- [ ] add phoenix.digest
- [ ] tweak phoenix.gen.html - expand explanation to include --no-model
- [ ] tweak phoenix.gen.html task to include test files generated
- [ ] replace list of phoenix tasks at the top

**Comment by ugisozols** [comment]
This can be closed as https://github.com/phoenixframework/phoenix_guides/pull/269 was merged.

**Comment by lancehalvorsen** [comment]
Thanks for the reminder! I also just updated the phoenixframework.org site.
