### ISSUE TITLE
Advanced Deployment Guide overrides port configuration

### ISSUE THREAD

**Issue by citizenparker** [phoenixframework/phoenix_guides#268]
Unless I'm missing something obvious, the way the advanced deployment guide recommends to set a default port doesn't work.

The guide currently recommends this:
```
config :hello_phoenix, HelloPhoenix.Endpoint,
  http: [port: {:system, "PORT"}],
  url: [host: "example.com"],
  cache_static_manifest: "priv/static/manifest.json",
  server: true,
  http: [port: 4001]
```

The wording makes me believe that it intends to set a default value of port 4001 when `PORT` is not passed in as an environment variable. However this _always_ sets the port to 4001, even when I specify the port via environment variable.

My understanding of exrm is too limited to recommend a better approach to this, but as far as I can tell the rest of the port configuration in this guide (like in the upstart file) doesn't do anything

**Comment by lancehalvorsen** [comment]
@citizenparker Thanks for pointing this out. You are correct, this is a documentation bug.

For now, you can remove the `http: [port: 4001]` line from `config/prod.exs` as long as you set a `PORT` environment variable before creating the release.

Sorry for any confusion this caused.

Currently, I am deep in the middle of a new set of testing guides, but revamping the entire way we document deployment is next on my list.

If you were inclined to submit a pull request for this guide, that would really be helpful. :^)

**Comment by citizenparker** [comment]
Wish I could! I don't know what the right recommendation here would be without diving into how exrm's conform dependency works. I gave up on this approach prior to getting too deep into that though.
