### ISSUE TITLE
How to use web.ex

### ISSUE THREAD

**Issue by paulcsmith** [phoenixframework/phoenix_guides#277]
It might be good to add a guide about using web.ex. It's very powerful, but also easy to abuse.
- How to customize controllers, views and channels
- What to put in them and what not to put in them
- Gotchas and pitfalls

For instance this bit of wisdom from @chrismccord 

> defining the function in web.ex leaks the implementation to all controllers. It can't be tested in isolation, it makes the code more difficult to reason about (where did this function come from?), it can't be imported from elsewhere, and stack traces can get confusing on where the error originates. So never inject functions within a quote (anywhere), unless you have a really good reason

I'd love to see that in a guide somewhere. I can start tackling this, but won't have time for a couple weeks so if someone wants to jump in, I'm fine with that.

**Comment by lancehalvorsen** [comment]
I'm all for this - clarity + helping people avoid problems.

I will be working on other areas of the guides for at least a few weeks as well. Pull requests from interested readers are welcome!

**Comment by leikind** [comment]
What can be said about it, really? Not much. web.ex is mentioned at least one time in the guides, and once you open it it becomes clear what it is. Its only purpose is to gather together all alases and imports for each type of web modules Phoenix has. The comment clock in the beginning of this file says it all.

**Comment by willykaram** [comment]
@lancehalvorsen @paulcsmith perhaps we could collect some of this sort of guidance into a Bonus Guide relating to 'Best Practices'? I think there's a fair amount of this sort of learning relating to a few topics which is acquired early on that may be good to share in this way.

**Comment by schnittchen** [comment]
What are thoughts about going beyond phoenix' concepts inside web.ex? I'm just about to add a :mailers section which a new phoenix project just lacks, but I can also see people adding their own category of concept below web/ and consequently add a section to web.ex.

I've done similar things in the past in Rails with a lot of success.

**Comment by willykaram** [comment]
@schnittchen sorry for not replying to the comment above, but I didn't see it until now. I'm not sure about that suggestion, as I'm not very familiar with the concepts that you mentioned. Do you perhaps want to create a draft write-up/PR of what you have in mind and myself or someone else could review?

**Comment by willykaram** [comment]
Here's an example of a helper function that recommends editing web.ex to for availability across all templates

https://github.com/code-lever/font-awesome-phoenix
