### ISSUE TITLE
Path functions insert && with empty maps

### ISSUE THREAD

**Issue by jeregrine** [phoenixframework/phoenix_guides#294]
I know I've seen this before, but I haven't been able to isolate the issue specifically

```elixir
iex(2)> App.Router.Helpers.project_path(CometApi.Endpoint, :index,  %{:filter => %{}, :include => %{}, :page => %{number: 0, size: 20}, :sort => [desc: :created_at], "format" => "json", "sort" => "-created_at"})
"/api/projects?&&page[number]=0&page[size]=20&sort[desc]=created_at&format=json"
```

**Comment by jeregrine** [comment]
Also I know the map has some weirdness in it, just wanted to get it down so that I don't forget it :)

**Comment by lancehalvorsen** [comment]
Thanks @jeregrine. 

Github Issues as the new Evernote? ;)

**Comment by jeregrine** [comment]
SHOOT I thought for sure I clicked the phoenix repo :( sorry.

**Comment by jeregrine** [comment]
Now here https://github.com/phoenixframework/phoenix/issues/973 :P

**Comment by lancehalvorsen** [comment]
:) no worries!
