### ISSUE TITLE
 persist/2 in D_controllers.md not available in Phoenix docs

### ISSUE THREAD

**Issue by 2kodes** [phoenixframework/phoenix_guides#298]
Hi, 
Reading through the chapter on controllers i found the lines below. 

"Besides put_flash/3 and get_flash/2, the Phoenix.Controller module has two other useful functions worth knowing about.

persist/2 takes conn and value. It allows us to save that value as a flash message in the session so that it can persist beyond the current request cycle."

Searching through phoenix docs however i could not find persist/2 in there. The closest match I found was persist_flash/2 which however seems to be a private function and hence unavailable.

**Comment by lancehalvorsen** [comment]
Thanks @2kodes! I'll take a look at this tonight. If you happen to figure out what this should be before then, a pull request would be really great!

**Comment by lancehalvorsen** [comment]
@2kodes thanks again. You are absolutely correct. There is no new public function to take the place of `persist/2`, so I deleted the reference.

**Comment by 2kodes** [comment]
You are welcome Lance.. 
Had Internet issues yesterday so couldn't respond.. 
Great job with the docs..  :)
