### ISSUE TITLE
Deployment introduction in wrong place

### ISSUE THREAD

**Issue by zigomir** [phoenixframework/phoenix_guides#305]
![phoenix-deployment-introduction](https://cloud.githubusercontent.com/assets/957321/8428932/4cb40530-1f23-11e5-8d40-2d76897921d0.png)

Currently on [http://www.phoenixframework.org/v0.14.0/docs](http://www.phoenixframework.org/v0.14.0/docs) deployment introduction page is at wrong place in navigation menu.

Also, I think url could be /v0.14.0/guides instead of /v0.14.0/docs. Is there a repository we can contribute to fix navigation?

**Comment by lancehalvorsen** [comment]
Thanks for reporting this @zigomir!

Apparently, when I created the new version in readme.io, quite a few files switched position in the left nav. All fixed now.

**Comment by lancehalvorsen** [comment]
Oh, and I forgot your second question. I'll have to look more closely into readme.io, but I think that path (version/docs) is set for us in their application.
