### ISSUE TITLE
Add Task.Supervisor guides

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix_guides#320]
// @jeregrine

**Comment by jsncmgs1** [comment]
I can take this if @jeregrine isn't to far into it.

**Comment by jeregrine** [comment]
@jsncmgs1 please do!

**Comment by jsncmgs1** [comment]
@jeregrine @chrismccord I wrote up what I imagine would be a good starting point for this guide, but I'd like some guidance on what else should be in here, as I don't want to just recreate the docs.

https://github.com/jsncmgs1/phoenix_guides/commit/3ec1ebb8a50226acf13b95cfaf731fd6a5710108

**Comment by jeregrine** [comment]
@jsncmgs1 I have one comment, but overall I think you should focus the guide more on "Running Tasks" and less specifically on Task.Supervisor. 

Focusing more on what you are trying to solve, less on the solution.

I think you should also make a note that if the Task fails it won't be retried and any information sent to it will be lost.

**Comment by jeregrine** [comment]
And possibly link to "task runners" or GenState for a system that might persist tasks and be more resilient to failure.

**Comment by jsncmgs1** [comment]
Cool, I'll take that advice and work on the next version.
