### ISSUE TITLE
Prep guides for 0.15 release

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix_guides#329]
I will tackle all non-ecto related changes, but I could use some help on the Ecto side as I've been heads down in channel work with the recent ecto changes. @lancehalvorsen have you started any updates in this area? I think @jeregrine is set to begin the updates if not.

**Comment by jeregrine** [comment]
Working on ecto now.

**Comment by jeregrine** [comment]
@lancehalvorsen looks like its already good! :+1:

**Comment by chrismccord** [comment]
Our controller generators use the non-bang variant with a case expression, so we need to bump those bits still

**Comment by lancehalvorsen** [comment]
I just merged @josevalim's PR for the Ecto Models Guide which should include the non-bang variants plus case expression. I'll look in the Mix Tasks Guide for any lingering changes.

/ @chrismccord @jeregrine

**Comment by lancehalvorsen** [comment]
Also, as I read through your Channel Guide PR @chrismccord, seems like the Channel Routes section of the Routing Guide needs to go away too, yes?

**Comment by lancehalvorsen** [comment]
Once we merge PR 330, there are four files we need to push to the site:
- Ecto Models
- Routing
- Channels
- Mix Tasks

**Comment by lancehalvorsen** [comment]
I just bumped the version number for the archive in the Installation Guide as well. Now there are five files to push.
* Installation

**Comment by lancehalvorsen** [comment]
I created a new version and moved over the changed docs. I also created a new blog post for update instructions. I haven't incorporated any of the comments to the upgrade gist yet, though. @chrismccord if you do incorporate them into the gist, let me know and I'll update the blog post. Otherwise, I'll verify and update as I get a chance.

I think this one is a wrap!

**Comment by chrismccord** [comment]
Thanks Lance! I'll handle the blog update side.

**Comment by lancehalvorsen** [comment]
Awesome! Thanks, Chris.
