### ISSUE TITLE
Links on the guides are not obvious

### ISSUE THREAD

**Issue by edmz** [phoenixframework/phoenix_guides#331]
The current style of the links, at least in the body of the document, makes them really hard to notice. They are not visible at a quick glance and sometimes are hard to notice due to the different shades of gray(ish) found in the text.

<img width="514" alt="screen shot 2015-07-29 at 5 37 36 pm" src="https://cloud.githubusercontent.com/assets/18996/8971783/39579030-3619-11e5-9be5-f2720fccd291.png">

IMHO, a simple underline would do wonders. Or even a background, but I am no designer.

<img width="460" alt="screen shot 2015-07-29 at 5 40 54 pm" src="https://cloud.githubusercontent.com/assets/18996/8971794/50ccab7e-3619-11e5-9ad9-759a55881c2c.png">

**Comment by lancehalvorsen** [comment]
Thanks for bringing this up, @edmz. As it happens, I'm not a designer either. :)

We host the guides with readme.io, which is a documentation-as-a-service company. Changing the css is a little more involved than opening a file on the filesystem and tweaking some values. I will look into this when I get a chance.

**Comment by chrismccord** [comment]
Bump. I was just browsing the guides and the links are really quite muted. Can we get a css tweak @jeregrine or @paulcsmith ?

**Comment by paulcsmith** [comment]
I can take this one. Should be a pretty quick fix! Thanks for the suggestion @edmz
