### ISSUE TITLE
The Heroku deployment guide is broken since HOST is nil on Heroku

### ISSUE THREAD

**Issue by peter** [phoenixframework/phoenix_guides#332]
I'm not sure what the proper fix for this is but the deploy didn't work for me since System.get_env("HOST") is nil on Heroku. I worked around this by doing:

heroku config:set HOST=myapp.herokuapp.com

Is the host needed in the prod config?

**Comment by lancehalvorsen** [comment]
Hi @peter, I'm curious, did you use the app name that Heroku generated for you, or did you give it a custom one?
