### ISSUE TITLE
Should we list versions for Phoenix and so on in snippets?

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix_guides#333]
Some guides, like [the exrm one](http://www.phoenixframework.org/docs/advanced-deployment), lists all deps:

```
  defp deps do
    [{:phoenix, "~> 0.13.1"},
     {:phoenix_ecto, "~> 0.4"},
     {:postgrex, ">= 0.0.0"},
     {:phoenix_html, "~> 1.0"},
     {:phoenix_live_reload, "~> 0.4", only: :dev},
     {:cowboy, "~> 1.0"},
     {:exrm, "~> 0.15.3"}]
  end
```

Because of the version numbers, I am afraid it can be confusing. Should we change it to something like:

```
  defp deps do
    [...,
     {:exrm, "~> 0.15.3"}]
  end
```

Or it is unlikely it would be confusing? Just give me a heads up and I can change this.

**Comment by lancehalvorsen** [comment]
I'm on the fence about this. On the one hand, having explicit version numbers sometimes helps people see that they have a problematic mix of versions in their own project, especially after upgrading.

On the other, these numbers are clearly brittle and many are probably out of date in these guides. Maintenance is key, but also quite 

On the third hand (?!), people have been good in the past about suggesting changes through the site when the versions are off.

Anybody else have a strong opinion on this?

**Comment by josevalim** [comment]
Ok, you have definitely thought about this, so let's keep the versions. Things are supposedly going to calm down soon anyway. :) Thanks @lancehalvorsen!
