### ISSUE TITLE
Channel guides should include token auth examples

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix_guides#337]
We have doc'd it here in phoenix, so should be a matter of transplanting:

https://github.com/phoenixframework/phoenix/blob/master/installer/templates/static/brunch/socket.js

**Comment by willykaram** [comment]
@chrismccord @lancehalvorsen Not sure if the above PR transplants the example as intended, but it not please LMK and I can revised accordingly.

**Comment by willykaram** [comment]
Apologies for the error with the prior PR/branch. I may have some further suggested revisions to this guide later in the week, but for now at least wanted to try and clean-up the prior commits and not leave the issue/PR hanging.
