### ISSUE TITLE
expand ecto guides to include "advanced" topics

### ISSUE THREAD

**Issue by schainker** [phoenixframework/phoenix_guides#341]
It took some munging to figure out how to use `mix phoenix.gen` to add arrays and maps to the ecto models at the command line, and there is more work to make sure the protocols are implemented correctly.  Might be useful for people who want to use `phoenix.gen` to generate models that take advantage of these features.  Since I don't think it fits under "basic" ecto usage, should the guides include an "advanced" ecto guide?

**Comment by chrismccord** [comment]
Yes this is something we have planned, but all contributors have been pretty busy as of late prepping things for 1.0. If you could draft an initial version and send a pull request, that would be great. We should have an expansion on the Ecto guides around associations very soon, but the arrays and maps  features could use a writeup

**Comment by schainker** [comment]
Sounds good, I'll get to work on it.

**Comment by lancehalvorsen** [comment]
I love to read things like your last comment. <3 Thanks @schainker!

**Comment by schainker** [comment]
Hello, so we have the following "short list" of topics for the advanced guide, roughly in order of importance as deemed by @chrismccord and my left brain: 

- maps
- arrays
- nested queries
- many-to-many associations
- subqueries and `Repo.aggregate`
- association preloading (and "suggested" or "effective" use)

Let's start with the first three and go from there?

**Comment by schainker** [comment]
Also, this guide assumes ecto 2.0.0-beta.2

**Comment by jeregrine** [comment]
@schainker any movement on this? Maybe we could help give feedback with a PR?

**Comment by jeregrine** [comment]
Hey everyone we're going to close this for now. Please create a new PR when a guide is created.
