### ISSUE TITLE
Mention more supported databases in Ecto guide

### ISSUE THREAD

**Issue by denisw** [phoenixframework/phoenix_guides#350]
Currently, the Ecto guide only says that only PostgreSQL and MySQL adapters exist for Ecto. However, the [README of Ecto](https://github.com/elixir-lang/ecto) also links to MSSQL ans SQLite adapters. It would be nice if these were mentioned too, so that people who need support for these databases know that Phoenix and Ecto can help them.

**Comment by lancehalvorsen** [comment]
@denisw, thanks for bringing this up. I agree. Care to submit a PR? :^)
