### ISSUE TITLE
Add guide on using non-js channel clients

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix_guides#355]
We don't need a ton of code samples or walkthrough, more informational with links to clients

objc: https://github.com/livehelpnow/ObjCPhoenixClient
java: https://github.com/eoinsha/JavaPhoenixChannels
c#: https://github.com/livehelpnow/CSharpPhoenixClient

**Comment by maxbeizer** [comment]
closed by #386 ?
