### ISSUE TITLE
Upgrade instructions for Phoenix 1.0

### ISSUE THREAD

**Issue by Alamoz** [phoenixframework/phoenix_guides#362]
Are you going to post upgrade instructions for 1.0? Thanks!

**Comment by lancehalvorsen** [comment]
I don't believe there are any upgrade instructions. There is a new installation archive, but I think that's it.

I'll leave this open for a bit so others can comment in case I got that wrong.

**Comment by Alamoz** [comment]
Should we use phoenix_ecto 1.1.0? So with my 0.17 app, do I change this:

  defp deps do
    [{:phoenix, "~> 0.17"},
     {:phoenix_ecto, "~> 0.4"},
     {:postgrex, ">= 0.0.0"},
     {:phoenix_html, "~> 1.1"},
     {:phoenix_live_reload, "~> 1.0"},
     {:cowboy, "~> 1.0"},
     {:exrm, "~> 0.15.3"}]
  end
end


To This:

  defp deps do
    [{:phoenix, "~> 1.0"},
     {:phoenix_ecto, "~> 1.1.0"},
     {:postgrex, ">= 0.0.0"},
     {:phoenix_html, "~> 1.1"},
     {:phoenix_live_reload, "~> 1.0"},
     {:cowboy, "~> 1.0"},
     {:exrm, "~> 0.15.3"}]
  end
end

I'm thinking we should also use newer versions of the other packages?

**Comment by Alamoz** [comment]
Or, are we supposed to create a new app and move over the code from the existing app?

**Comment by Alamoz** [comment]
OK, so if you completely reinstall the 1.0 version of phoenix and create a new app, this is what mix.exs looks like (:exrm is no longer present):

  defp deps do
    [{:phoenix, "~> 1.0.0"},
     {:phoenix_ecto, "~> 1.1"},
     {:postgrex, ">= 0.0.0"},
     {:phoenix_html, "~> 2.1"},
     {:phoenix_live_reload, "~> 1.0", only: :dev},
     {:cowboy, "~> 1.0"}]
  end

So I'm guessing there are other changes that perhaps make upgrading from version 0.17 difficult. So to be safe I guess one should do a fresh Phoenix installation, create a new app, then copy over the files from your 0.17 (or earlier) app.

**Comment by chrismccord** [comment]
> So I'm guessing there are other changes that perhaps make upgrading from version 0.17 difficult.

No! There are no changes required from 0.17 -> 1.0 other than bumping your phoenix dep. `:exrm` was never a dependency so you must have added it to your project. You don't need to generate a new project or copy any code. Simply bump phoenix to "~> 1.0.0" and mix deps.get

**Comment by Alamoz** [comment]
What about :phoenix_html getting bumped to 2.1? Will the compiler automatically change that in mix.exs?

I went ahead and did a fresh install and it is OK. Don't know how :exrm got in mix.exs, it must have been part of the template at some point.

Thanks again, looks great!

**Comment by Alamoz** [comment]
Ah, of course, :exrm was added to build releases. I only look at this app when you release upgrades. I'm using Phoenix for an api that serves json from Ecto queries and it works so well I don't even have to think about it, which means I also forget things about it.

**Comment by lancehalvorsen** [comment]
Thanks @Alamoz, I'm going to close this now. As Chris said, just bump your version of Phoenix and re-get the dependencies.
