### ISSUE TITLE
Use Ruby Syntax Highlighting?

### ISSUE THREAD

**Issue by clessg** [phoenixframework/phoenix_guides#372]
I've been reading through the Guides, and one thing that's a little jarring is the lack of code syntax highlighting. I assume this is because ReadMe.io doesn't have Elixir highlighting. So I was wondering if it might be possible to use Ruby syntax highlighting until they get support for it, considering how similar the languages are.

I apologize for being OCD.

**Comment by lancehalvorsen** [comment]
Hi @clessg, no need to apologize! I can understand your hope for Elixir syntax highlighting, but I don't think that changing the markdown for the guides to use Ruby syntax is the best solution. Ideally, readme.io would support Elixir natively. If this is important to you, please get in touch with the folks from readme.io with your request. We've found them to be responsive in the past.

Good luck, and thanks for reporting this!

**Comment by clessg** [comment]
Thank you for the kind reply! They weren't kidding when they said the Elixir community is full of nice people. I will try getting in touch with readme.io.

**Comment by lancehalvorsen** [comment]
:^)  and  :+1:

**Comment by davidspiess** [comment]
@clessg Have you got any response already? ATM I find it really difficult to grasp the examples, so i basically stick with github, which has proper syntax highlighting.

**Comment by clessg** [comment]
Sadly they never responded.

**Comment by gilbertkennen** [comment]
[It seems](https://readme.readme.io/docs/code-samples) that ReadMe.io uses [CodeMirror](http://codemirror.net/index.html) modes for their syntax highlighting. If an Elixir mode were developed, then they would probably just make it so, but probably not before.

**Comment by dummey** [comment]
For anybody who arrives here from google, syntax in the guide will be achieved via #391
