### ISSUE TITLE
Add seeding data as bonus guide

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix_guides#376]

**Comment by willykaram** [comment]
@chrismccord @lancehalvorsen what should the letter be that precedes the Seeding Data guide? Sorry if I missed that somewhere in the docs/contributing guidelines?

**Comment by ybur-yug** [comment]
@chrismccord @willykaram If one of you could elaborate I'd be happy to contribute this if it isn't being worked on :smile:

**Comment by willykaram** [comment]
@ybur-yug thanks offering to help out. Any comments or feedback on the above draft would be really appreciated. I started on the draft of this guide here which we could work at improving: https://github.com/willykaram/phoenix_guides/blob/seeding-data-guide/bonus_guides/X_seeding_data.md

I'm guessing @lancehalvorsen and @chrismccord will have some feedback/revs too.

**Comment by ybur-yug** [comment]
@willykaram awesome, I'll check it out now

**Comment by willykaram** [comment]
@ybur-yug thx that'd be great

**Comment by ybur-yug** [comment]
@willykaram left a couple comments :+1:

**Comment by willykaram** [comment]
Thanks a *lot* for that @ybur-yug, you rock. I'll have a look tonight tomorrow and incorporate what I can technically. And if it's something beyond my experience/judgment, then hopefully @chrismccord and/or @lancehalvorsen can review/revise.

**Comment by jeregrine** [comment]
@willykaram could you PR these changes? Thanks!

**Comment by willykaram** [comment]
@jeregrine y, will do, was just waiting for feedback/green light to confirm
that they were ok

**Comment by ybur-yug** [comment]
@willykaram if there is any more review needed for this, or additions etc feel free to let me know and I'd be happy to contribute.

**Comment by willykaram** [comment]
@jeregrine I just completed the revisions to the draft seeding guide in PR #465, I also included the suggestions from @ybur-yug that I was experienced enough to include. He had some additional suggestions that I think he's going to add to and that we can ideally include in an other PR once he' ready and that perhaps either you or @lancehalvorsen could review.

**Comment by willykaram** [comment]
@jeregrine @lancehalvorsen  just following up on this issue to see if there's anything we can do to advance or update the guide, or whether we could try to wrap this up and close the issue?
