### ISSUE TITLE
Adding link to a screencast on deploying Phoenix to Heroku

### ISSUE THREAD

**Issue by gjaldon** [phoenixframework/phoenix_guides#383]
Hi there! I made a screencast for [Deploying Phoenix to Heroku](http://phoenixscreencasts.com/episodes/8-deploying-phoenix-to-heroku) and think it would be helpful to have it mentioned in the guides for Heroku Deployment.

What do you think?

**Comment by lancehalvorsen** [comment]
Hi @gjaldon! Thanks for this suggestion. At this point, we're only linking to external content in the two "learning" guides, and I think we'll stick with that strategy. Even in those guides, we're only linking to Chris' long-form conference videos, iirc.

Thanks again for making this suggestion. :)
