### ISSUE TITLE
Rework the current guides

### ISSUE THREAD

**Issue by alan-andrade** [phoenixframework/phoenix_guides#396]
Hello everybody,

As I was skimming through the guides, I felt it was easy for me to get distracted or miss the point.
I believe there are some paragraphs where we can trim details and preambles so that the content can be absorbed faster. (Or this could be attributed to my not so great reading skills ;) )

Here is an example of what I have in mind.

The section [Adding Pages](http://www.phoenixframework.org/docs/adding-pages) starts like this
> Our task for this guide is to add two new pages to our Phoenix application. One will be a purely static page, and the other will take part of the path from the url as input and pass it through to a template for display. Along the way, we will gain familiarity with the basic components of a Phoenix application: the router, controllers, views and templates.

Let's break it down.
> Our task for this guide is to add two new pages to our Phoenix application.

We know that from the title. The title is not as specific as this sentence, but I don't think being specific is important right now.

>  One will be a purely static page, and the other will take part of the path from the url as input and pass it through to a template for display.

These could be subsections / subheaders of the guide. We could remove them from here and give detail in the subsections once we've heard about "templates" and "paths". 

> Along the way, we will gain familiarity with the basic components of a Phoenix application: the router, controllers, views and templates.

I think users are looking forward for that anyway. Its implicit.

I feel like this first paragraph could go and the guide wouldn't loose anything.

Before I jump into this task (which I'm really exited about) I wanted to ask everybody if this is something that has come up before ? Or if you think this make sense ? Should we keep pushing this ?

Thank you ! <3

**Comment by lancehalvorsen** [comment]
Hi @alan-andrade,

First, thanks so much for taking the time to write this up. You clearly care about the guides and want to make them better.

Here are my thoughts.

It's important to lay out the path that lies ahead for readers. It helps them prepare a skeleton of a mental model to hang all the coming details on. Introductory paragraphs have existed in non-fiction writing for a long, long time for exactly this reason.

Writing is not coding. DRY is not entirely applicable to long-form prose the way it is to an application.

The guides are intended to have value for the widest possible audience - even those who have never written a web application before. While sometimes we can make inferences, we shouldn't expect others to have to make those inferences themselves. I think that providing more information to help those with less experience is preferable to cutting information which more experienced readers might want to skip.

Having said all that, editing is really important. If there is irrelevant or redundant information, we should cut it. I personally don't feel the paragraph in question is an example of that.

I'll leave this issue open for you or others to comment. Maybe I'm completely wrong on this!  :^)

**Comment by alan-andrade** [comment]
Hello @lancehalvorsen !

I apologize for taking so long. I was really excited about this topic so I gave it a shot. I wanted to learn more about what I'm actually proposing. I wrote [this blog post](http://alan-andrade.github.io/PhoenixIn10Minutes/) to get a better feeling of what I'm actually proposing. 

It was really fun to write !!! I had to infer rails experience though. My goal was to share how fast is to setup a web API with Phoenix. I think it's amazing how fast it could be done. When I opened this ticket I think I was biased by that.

I going to keep writing about Elixir and Phoenix and hopefully I can learn something that could benefit us all. I appreciate the reply ! and given the amount of conversation in this issue I believe you're not wrong at all.  :smiley:

**Comment by lancehalvorsen** [comment]
Hi @alan-andrade,

Thanks for following up. Glad that you had so much fun writing up the blog post! I think that the tone and style of writing you've adopted is really appropriate for blogging, and I encourage you to continue. :)

I don't think that such a radical change is the right thing for these guides, though. 

Best of luck with your blog!

**Comment by alan-andrade** [comment]
I agree with you. That would be radical and I don't think that's right.

Thanks a lot for the best wishes. I'm starting to really like this community :heart:
