### ISSUE TITLE
Search bar becomes too long on focus

### ISSUE THREAD

**Issue by armed** [phoenixframework/phoenix_guides#397]
Hi, .focus class sets search bar's width to 250px, which makes browser(chrome, ff, safari) to move it below menu line.
<img width="518" alt="search-bar" src="https://cloud.githubusercontent.com/assets/223060/10415060/a79debe4-700b-11e5-927b-0cc3526dc65a.png">
Setting with to 240px fixes this issue.

**Comment by lancehalvorsen** [comment]
Thanks for reporting this, @armed! I wish that I could act on it. We currently host the guides with readme.io. We have access to customize some of the styling, but not all of it. This particular piece is out of our control - at least I was not able to find a way to change it in their application.

Thanks again for taking the time to let us know!

**Comment by armed** [comment]
Hi, @lancehalvorsen. Thanks for quick reply. 

I've just created my own account on readme.io and found "Custom CSS" option in admin panel.
<img width="1163" alt="screen shot 2015-10-12 at 9 08 35 am" src="https://cloud.githubusercontent.com/assets/223060/10420982/01c9f0d0-70c1-11e5-9e6e-8d5e450678a3.png">
The CSS in that textbox is inserted in header of each page. I think this snippet will solve long search bar issue:
```css
.header .searchbox.focus input {
  width: 240px;
}
```

**Comment by jeffkreeftmeijer** [comment]
I was able to reproduce this issue in a separate documentation project on http://readme.io as well. I've sent an e-mail to their support address linking to this issue so they can take a look, as this is seems to be a problem for all of their users.

**Comment by armed** [comment]
@jeffkreeftmeijer, this issue occurs only if width of all menu items in nav bar exceeds some number, which occurs on phoenix site. I think they (readme.io) don't have to dynamically change width of search bar, it's up to customer to chose whether to make less menu items or shrink search bar.

**Comment by jeffkreeftmeijer** [comment]
Hey @armed,

While this issue only occurs for specific menu widths on specific window sizes, it's reproducible in a fresh http://readme.io project. I thought they should know about it, so they can make sure it works nicely for everyone out of the box. Also, them fixing it would save us a stylesheet override. 

![screen shot 2015-10-12 at 08 49 44](https://cloud.githubusercontent.com/assets/43621/10423181/0f8edf16-70c4-11e5-9810-0e77cfa124b3.png)

Without going into too much detail about how I think they should fix it here, they could make sure that the search bar doesn't grow more than will fit, or that it's already on the next line before becoming active if the active bar won't fit, so it doesn't jump around.

**Comment by armed** [comment]
Thanks, @jeffkreeftmeijer, I got it. You are right.

**Comment by lancehalvorsen** [comment]
Yes, I believe having readme fix it on their end is a better solution. :)

And an extraneous explanation:

I don't believe I worded my original response correctly. Yes, we can override the css, but the application doesn't give us specific control of that widget - meaning that readme isn't guaranteed to respect our css for it.

Assuming we would override the search styling, if readme changes the classes or scoping, we could end up with another bug, or the original bug back, now with an unused block of css cruft.

**Comment by jeffkreeftmeijer** [comment]
I've had contact with Gregory and Marc at Readme.io. Here's what happened;

They fixed it for the Phoenix website, so now the search bar works properly when the website is in full width. If the window becomes narrower than 1000px, the issue remains. I can't check in Readme.io, but I think they did exactly what @armed suggested, with a stylesheet override. They also told me they'll be rolling out a redesign this month that fixes a lot of issues like this one, so we might have to wait for that.

I've tried messing around a bit, but could only get it to work by making the input's container 250px wide, so it moves to the next line even before activating the input. That solves the problem of it popping over to the next line when becoming active, though.
