### ISSUE TITLE
Plug Guide - Confused

### ISSUE THREAD

**Issue by bmalum** [phoenixframework/phoenix_guides#404]
Hey 😊 
First of all, the `Guides` are the best ones I have ever read, explain everything and the first API is easy and fast up. But if you get deeper in Phoenix without being a Elixir Coder it is hard to understand the Plug mechanism.

My Question are:
* Where are the Plugs located? 
* How can the be included via dependencies? 
* Is a Module Plug always a Plug for connection transformation? 
* Naming Scheme for a Plug?
* Good Example for a Plug to look at? 

I would love to write my approach for my first Elixir Plug for Phoenix, but i struggled on this questions. I looked at the [Plug Dokumentation](http://hexdocs.pm/plug/extra-readme.html) and the [Plug.Session.Memcached](https://github.com/gutschilla/plug-session-memcached) but i did not answer my Question.

**Comment by lancehalvorsen** [comment]
Hi @bmalum,

Thanks very much for writing this up! We definitely want to provide the best information possible for people who are new to Phoenix and Elixir. Thanks also for the kind words about the guides. :)

I'm unsure about how many of your questions should be answered in the Guides and how many are better suited to the Phoenix mailing list or StackOverflow. I'm curious what your thoughts are about that.

Here's some info that I hope will answer your questions. 

The plugs that exist in a new Phoenix application live in Phoenix itself. Developers don't need to do anything extra to include them in an application. User defined plugs can go in either /web/plugs, where they will be automatically recompiled in dev, or /lib/plugs, where they won't. In either directory, they will be part of your application without doing anything special to include them.

All plugs must take connection structs as their first argument, and they all must return connection structs. What they do with the connection struct in the body of the function is up to the plug itself.

You can name a plug whatever you want, I suppose. It's really just a module or a function.

The Plug repo on GitHub is full of plugs, not surprisingly. :^)
https://github.com/elixir-lang/plug/tree/master/lib/plug

Hope this helps!

**Comment by bmalum** [comment]
Hi @lancehalvorsen, 

Thank you for all the Information. I just thought a Plug need more "magic" - i will let the community know and share my Plug also on Github, if i get it working, but now it does not seem too hard. 

Thank you and all of the Elixir and Phoenix Framework i like it so much already 😊

**Comment by lancehalvorsen** [comment]
We favor explicitness over magic in Elixir. :smile: . Glad you're enjoying Elixir and Phoenix!
