### ISSUE TITLE
Note about adding :ssl to mix.exs for SSL to work.

### ISSUE THREAD

**Issue by dsky** [phoenixframework/phoenix_guides#430]
I had to add `:ssl` to applications in my mix.exs file for https to start working. 
Maybe it would be better to make a note in the guide on SSL about that?

**Comment by jeregrine** [comment]
@dsky could you pr?

**Comment by blackfist** [comment]
This is a pretty old issue, and I notice that the SSL guide [here](http://www.phoenixframework.org/docs/configuration-for-ssl) does show `:ssl` being added to the application list in `mix.exs`. Is this issue still valid?
