### ISSUE TITLE
Problem and inconsistency in the Exrm Releases guide

### ISSUE THREAD

**Issue by sashaafm** [phoenixframework/phoenix_guides#434]
Hello, 

I've been following the Exrm Relases guide from the ver. 1.0.0 and there's a problem at the beginning about the dependencies. The guide states the following:

ADD EXRM AS A DEPENDENCY
To get started, we'll need to add {:exrm, "~> 0.15.3"} into the list of dependencies in our mix.exs file.

  defp deps do
    [{:phoenix, "~> 1.0.3"},
     {:phoenix_ecto, "~> 1.1"},
     {:postgrex, ">= 0.0.0"},
     {:phoenix_html, "~> 2.1"},
     {:phoenix_live_reload, "~> 1.0", only: :dev},
     {:cowboy, "~> 1.0"},
     {:exrm, "~> 0.19.9"}]
  end

First it asks for version 0.15.3 of exrm, but in the code it says version 0.19.9. First I tried with the version 0.19.9 and I got an error with :erlx saying it couldn't compile and to try to compile, update or clean it alone. 

I looked again and changed to version 0.15.3 and everything worked fine. I'm using version 1.1.1 of Elixir in a AWS Ubuntu 14.04 image.

**Comment by bmalum** [comment]
Interesting, `exrm 0.19.9` works fine for me with all projects so far. Just preparing a PullRequest to fix it to `0.19.9` - but i will wait until your problem is fixed.

**Comment by jeregrine** [comment]
This has been updated :-)
