### ISSUE TITLE
Add a guide, or section for using view's for JSON representation

### ISSUE THREAD

**Issue by jeregrine** [phoenixframework/phoenix_guides#438]
I can take this one, starting in the new Year, but if someone wants to take it sooner please do. 

Basically show examples of 
```elixir
def render("index.json", %{data: data}) do
   %{ id: data.id }
end
```

Why using your view this way is a good way to do it.

**Comment by ybur-yug** [comment]
@jeregrine where would this optimally be located, just after the standard rendering stuff in the views guide? I've been building JSON API's mostly lately so I'm quite familiar and would be happy to chip on this one as well (I've left a few other comments, it seems there are a lot of help wanted tags). Let me know what your folks' primary priorities are and I'll try to distribute some of my help wherever youd like 👍

**Comment by jeregrine** [comment]
@ybur-yug happy to hand off :-)

**Comment by jsncmgs1** [comment]
Is this being actively worked on?  If not, I can start this, and if it has been I'd like to help if needed.

**Comment by jsncmgs1** [comment]
I wrote up a draft to hopefully get this started:
https://github.com/jsncmgs1/phoenix_guides/blob/view_json_enhancement/E_views.md#rendering-json

**Comment by jeregrine** [comment]
@jsncmgs1 first come first serve, please open a PR :-)

**Comment by ybur-yug** [comment]
@jsncmgs1 I had a draft started but yours looks a lot better. Open the PR and I'd happily proofread + run any example code etc. :)

**Comment by jsncmgs1** [comment]
@jeregrine I forgot to add "closes" to the PR. Sorry!
