### ISSUE TITLE
Add a guide on sending email using SMTP rather than mailgun

### ISSUE THREAD

**Issue by lpil** [phoenixframework/phoenix_guides#447]
I think it'd be great if we had example of a more common + generic method of sending emails rather than just one specific third party service. :)

**Comment by jeregrine** [comment]
@lpil could you PR a guide?

**Comment by lpil** [comment]
Hum. I don't see why not. Unsure when I'll get the time though.

**Comment by jeregrine** [comment]
@lpil cool :-)
