### ISSUE TITLE
Typo in http://www.phoenixframework.org/blog 'Upgrading from v1.0 to v1.1' 

### ISSUE THREAD

**Issue by yeongsheng-tan** [phoenixframework/phoenix_guides#457]
#### Code block minor fix in 'GETTEXT (OPTIONAL)' section
Second code block:
From ->
```elixir
+  applications: [:phoenix, :phoenix_html, :cowboy, :logger, :gettext
+                 :phoenix_ecto, :postgrex]]
end
```

To ->
```elixir
+  applications: [:phoenix, :phoenix_html, :cowboy, :logger, :gettext,
+                 :phoenix_ecto, :postgrex]]
end

**Comment by lancehalvorsen** [comment]
Thanks @yeongsheng-tan! I just fixed this on phoenixframework.org.

@chrismccord, just a note here in case you wanted to add the comma after `:gettext` to the upgrade gist.
