### ISSUE TITLE
Issues with upgrading guide

### ISSUE THREAD

**Issue by HeroicEric** [phoenixframework/phoenix_guides#460]
Found a few issues in [the blog post about upgrading from 1.0 to 1.1](http://www.phoenixframework.org/blog/upgrading-from-v10-to-v11). I wasn't able to find a place to make a PR but if there is a way please let me know and I'll do so :smile: 

The diff for `web/web.ex` lines 42 and 77 does not match https://github.com/phoenixframework/phoenix/commit/f268a31af1f1da46ae59d7cb1fce3cc480977342 (missing the removal of `import Ecto.Model`)

**Comment by HeroicEric** [comment]
It's also missing the diff here https://github.com/phoenixframework/phoenix/commit/1b858cbbebc86f0095dc17e1107ed9998927086f for the files in `test/support`

**Comment by lancehalvorsen** [comment]
Hi @HeroicEric, thanks for this!

These blog posts come directly from the [upgrade guides](https://gist.github.com/chrismccord/557ef22e2a03a7992624) in the Phoenix repo. There are no local files in this repo to make a PR from, but we create the posts in the hosting application. (I hope that's clarifying more than confusing. :) )

I'll re-verify and fix this up soon. Thanks again!

**Comment by jeregrine** [comment]
@lancehalvorsen @HeroicEric best thing you can do is post a comment on the gist https://gist.github.com/chrismccord/557ef22e2a03a7992624
