### ISSUE TITLE
Consider changing the recommended C# channel client

### ISSUE THREAD

**Issue by jerel** [phoenixframework/phoenix_guides#464]
I needed a C# channel client and couldn't get the one recommended in the guides to work. I ended up using this one which is up-to-date as of Phoenix v1.1.1 and works flawlessly so far. https://github.com/jfis/dn-phoenix

Here is my original issue on the "official" C# client: https://github.com/livehelpnow/CSharpPhoenixClient/issues/2

I'm happy to do a PR to change the link if you want it done.

**Comment by Joshua-Ferguson** [comment]
The [jfis](https://github.com/jfis/dn-phoenix) client's readme also says: 

> a c# port of the phoenix framework js client (at 1.1.1, commit c09e98e) funded by @livehelpnow

which leads me to believe that the client @[livehelpnow](https://github.com/livehelpnow/CSharpPhoenixClient/) may no longer be maintained.

**Comment by jeregrine** [comment]
@jerel please PR. Sorry for slow response here.
