### ISSUE TITLE
Add note about database configuration

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix_guides#471]
ref https://github.com/phoenixframework/phoenix/issues/1528#issuecomment-181138011

**Comment by bjfish** [comment]
It's nice when the D.B. command on how to create the default user/password is given. For example, here https://github.com/hexpm/hex_web/blob/master/README.md

**Comment by blackfist** [comment]
Is there some additional work that needs to be done with this issue? It appears that a PR was merged that addressed everything, but then a couple weeks ago the help wanted tag was added. What's left to be done on this?

**Comment by jeregrine** [comment]
@blackfist good call I will close this one.
