### ISSUE TITLE
Reference to match/3 in the router guide

### ISSUE THREAD

**Issue by Gazler** [phoenixframework/phoenix_guides#472]
I did some exploration based on this question https://stackoverflow.com/questions/35367759/what-is-the-match-3-function-in-the-context-of-the-phoenix-framework

There are references to `match/3` https://github.com/phoenixframework/phoenix_guides/blob/master/C_routing.md#resources which does not exist in Phoenix. I think we should clarify which function we mean.

My guess was that it was a reference to the private `match_route/4` function.

**Comment by ybur-yug** [comment]
I could work on this one and get it up for review with the other batch of PR's I already have open if no ones stepped in on this one yet @Gazler

**Comment by willykaram** [comment]
@ybur-yug Did you still want to try and assist with this issue?

**Comment by ybur-yug** [comment]
@willykaram sorry I just got back from vacation and have been prepping for a conference so I got way behind in notifications. I would be happy to and also commented in the bigger guides-overhaul issue.

**Comment by mcelaney** [comment]
https://github.com/phoenixframework/phoenix_guides/pull/802
