### ISSUE TITLE
Update Elixir / Erlang / Node installation instruction for Ubuntu / Debian

### ISSUE THREAD

**Issue by riverrun** [phoenixframework/phoenix_guides#477]
On Ubuntu / Debian systems, the repository's version of Elixir, Erlang and Node is usually quite old, so perhaps we can add some information in 'E_installation.md' about ways of installing newer versions of these apps.
For Elixir and Erlang, I think the best option is to replicate the advice given in the 'Installing Elixir' page - that is, to add the Erlang Solutions site to the available repositories, update, and install `esl-erlang` and `elixir`.
For Node, I've found that [this solution](https://github.com/nodesource/distributions) is a good way of keeping it up-to-date.

**Comment by jeregrine** [comment]
@riverrun could you PR this change? Thanks!

**Comment by Oxyrus** [comment]
I've created a shell script to install Elixir on Ubuntu/Debian systems, https://github.com/elixir-espanol/one-shot-elixir-installation perhaps the steps could be written in the guide.

**Comment by riverrun** [comment]
I'll send a PR sometime within the next few days.
