### ISSUE TITLE
Typo in Upgrading guide 1.1.1 to 1.1.2

### ISSUE THREAD

**Issue by sashaafm** [phoenixframework/phoenix_guides#496]
In the very latest bit of the upgrading guide of 1.1.1 to 1.1.2 in the "Test It" section there's the following typo:

$ mix** phoeinix.server**
07 Jan 16:16:59 - info: compiled 5 files into 2 files, copied 3 in 1.2 sec

should be:

$ mix** phoenix.server**
07 Jan 16:16:59 - info: compiled 5 files into 2 files, copied 3 in 1.2 sec

I posted this here since if I'm not mistaken these posts can't be PR'ed :)

**Comment by jeregrine** [comment]
@sashaafm best way is to click the linked gist and make a comment.
