### ISSUE TITLE
Link broken in docs-controller 

### ISSUE THREAD

**Issue by vishaldeepak** [phoenixframework/phoenix_guides#500]
In docs controller - under subsection - http://www.phoenixframework.org/docs/controllers#section-setting-the-content-type. In the last sentence the text [mime.types], which redirects to https://github.com/elixir-lang/plug/blob/master/lib/plug/mime.types, is broken. 
Was trying to find a suitable replacement file to raise a pull request, could not find one though

**Comment by jeregrine** [comment]
Thanks @vishaldeepak I fixed it in master, I did not link the issue like a dingus though.!

**Comment by vishaldeepak** [comment]
thanks for fixing @jeregrine, though I could not get  -- ` I did not link the issue like a dingus though.!`.

**Comment by jeregrine** [comment]
@vishaldeepak sorry, I meant that I should have linked the commit to this issue. I forgot to do that :-)
