### ISSUE TITLE
Heroku deploy section missing `git add Procfile` (needs one line added)

### ISSUE THREAD

**Issue by tronathan** [phoenixframework/phoenix_guides#508]
It appears that the documentation for Heroku deployment is missing:

```
git add Procfile
```

In the section referenced here: http://www.phoenixframework.org/docs/heroku#section-deploy-time-

```
$ git add config/prod.exs
$ git add web/channels/user_socket.ex
$ git commit -m "Use production config from Heroku ENV variables and decrease socket timeout"
```

In this case, the Procfile will not be added and the project will not work.

The fix is to add:

```
$ git add Procfile
```

To the documentation under "Deploy Time!"

**Comment by jeregrine** [comment]
@tronathan could you PR this in quick? Thanks!

**Comment by ybur-yug** [comment]
@jeregrine I threw it together quickly in #510

**Comment by ybur-yug** [comment]
@tronathan @jeregrine I think we can close this one now that #510 is merged
