### ISSUE TITLE
Docker deployment guide? 

### ISSUE THREAD

**Issue by dmitrinesterenko** [phoenixframework/phoenix_guides#525]
Hi All,

I notice in the [deployment guides](https://github.com/phoenixframework/phoenix_guides/tree/master/deployment) we have EXRM or Heroku guides. Any interest in a Docker + let's say Elastic Beanstalk guide? I could write one up similar to Heroku. Here's a [project](https://github.com/dmitrinesterenko/sample_phoenix_elasticbeanstalk/) where I've experimented with this deployment.

**Comment by jeregrine** [comment]
@dmitrinesterenko absolutely, could you PR what you have in mind?

Thanks!!

**Comment by dmitrinesterenko** [comment]
I am doing #124 first as that's good to have in the guide before the bonus or deployment guides. Will do propose a PR for this after.
