### ISSUE TITLE
Ecto Basics Guide

### ISSUE THREAD

**Issue by radar** [phoenixframework/phoenix_guides#526]
Hi there, just looking to gauge if there's any interest in having my [Ecto Basics](https://github.com/radar/guides/blob/master/ecto.md) guide as an official guide in this repository. I understand that Phoenix _can_ be used without Ecto, but since it comes installed by default, I think it would be very useful to have a guide that covers the basics. That's similar to how the Rails guides has the [Active Record Querying Guide](http://guides.rubyonrails.org/active_record_querying.html).

If there's some interest in that, then I'll tidy up the guide and submit a PR for this repo.

**Comment by ybur-yug** [comment]
@radar if theres any interest and you want some help with that feel free to ping me. I think it would be useful.

**Comment by radar** [comment]
Hey @ybur-yug, I've started work on this over in the Ecto repo: https://github.com/elixir-ecto/ecto/pull/1516. I'll close this issue now.
