### ISSUE TITLE
Ecto Guide Needs some updating?

### ISSUE THREAD

**Issue by mneumark** [phoenixframework/phoenix_guides#529]
I am a newbie and am learning this stuff but I know the last couple weeks have introduced some big changes for Ecto. 2.0 came out and made some significant changes. Phoenix has adapted and now uses Ecto 2.0.

But it seems the guide has not yet adjusted. According to the changelog for Ecto 2.0, changesets call `cast/3` instead of `cast/4` and we use `validate_required/3` instead. And of course defaulting to `%{}` instead of `:empty`.

Also, Phoenix Gen outputs significantly different models now.

I am too novice at this point to introduce corrections I feel. I am just knowledgable enough to know that something isn't fitting correctly.

**Comment by jeregrine** [comment]
@mneumark recently there was a large update to Phoenix, Elixir and Ecto. We need to update the site, its a WIP,

**Comment by dougselph** [comment]
Any guess as to when a v1.2 tagged Guides set gets posted to the site? I understand it's a large undertaking with with so many updates dropped last week

**Comment by jeregrine** [comment]
@dougselph no timeline right now.

@mneumark if you could make an issue for each thing you find as you go through it will be easier to chunk.

**Comment by mneumark** [comment]
@jeregrine Will do!

**Comment by ybur-yug** [comment]
This also can be closed as of the merge of #534
(CC @Gazler or whomever would be good to close it)

PS sorry for blowing up your inbox with tags @Gazler I <3 you for reviewing :)

**Comment by Gazler** [comment]
I meant to close these but totally forgot. Thanks for the reminder!
