### ISSUE TITLE
Security Guide

### ISSUE THREAD

**Issue by keithn** [phoenixframework/phoenix_guides#540]
Need a guide on security and authentication with Phoenix

**Comment by ybur-yug** [comment]
@keithn these are really two different topics. Security is something with a currently open issue:

[Issue 531](https://github.com/phoenixframework/phoenix_guides/issues/531) is currently open to handle things such as parameter sanitization and its related pieces, relating to security.

For authentication, there is currently [another issue](https://github.com/phoenixframework/phoenix_guides/issues/337) that is open as well. However, there is currently some robust documentation on `Phoenix.Token` already which can utilized [here](https://hexdocs.pm/phoenix/Phoenix.Token.html).

**Comment by jeregrine** [comment]
I agree with @ybur-yug lets focus on Phoenix.Token guide
