### ISSUE TITLE
Problem with using json guide

### ISSUE THREAD

**Issue by katgironpe** [phoenixframework/phoenix_guides#542]
It seems necessary enclose parameters within `()`:

```elixir
def show(conn, %{"id" => id}) do
  json conn, %{id: id}
end
```

I followed this and have: 

```elixir 
json conn, %{users: results}
```

But got undefined for `json`.

I changed it to:

```elixir 
json(conn, %{users: results})
```

It worked! I can confirm when I have time to create another app with the latest version of Phoenix.

**Comment by katgironpe** [comment]
Seems like a different problem. Going to close for now.

**Comment by rstacruz** [comment]
are you using `|>` by any chance?

```elixir
  conn
  |> json %{user: user}
  |> put_status(200)
```

Parens will change what this evaluates to. That might be one reason why you got that error :)

**Comment by katgironpe** [comment]
@rstacruz no I wasn't piping. But yes, there was something else wrong my code.
