### ISSUE TITLE
A warning note about defining scopes?

### ISSUE THREAD

**Issue by aerosol** [phoenixframework/phoenix_guides#551]
Hi, spoke to @josevalim before opening this ticket.

If you use custom "namespacing" scheme and the scope's module prefix accidentally matches an existing module (e.g. a controller), the compiler gets a false hint about module cross references. With an app large enough, this can lead to a situation when saving a single eex template causes a massive and unnecessary recompilation. The problem is difficult to trace. Perhaps it's worth putting a word of warning somewhere?

Example of "don't":

```elixir
scope "...", MyApp.Controllers.ExistingController do
  # ...
end
```

"Do", instead:

```elixir
scope "...", MyApp.Controllers do
  # ...
end
```

cc @zoldar

**Comment by josevalim** [comment]
Documented here: https://github.com/phoenixframework/phoenix/commit/2e32b8bb532d521af03c56f6f7a9ed14cb272ffb :)
