### ISSUE TITLE
'File Uploads' guide improvement 

### ISSUE THREAD

**Issue by sobolevn** [phoenixframework/phoenix_guides#552]
When dealing with phoenix it was not really clear for me at the first sight: how to store user uploaded files. There's no special folder or path defined for this. 

Coming from `django`-world, there we have `media/` folder which is the default one.

Maybe [this guide](https://github.com/phoenixframework/phoenix_guides/blob/427021c900e18c22739c9b476a9b629215bc2c83/bonus_guides/H_file_uploads.md) could be improved to specify the right way (an location) to store uploaded files locally? Leaving `s3` out of scope.

This issue is based on [this question](http://stackoverflow.com/questions/38865226/where-should-i-store-user-uploaded-files-and-images-in-phoenix-elixir/38866242#38866242) on SO.

**Comment by omin** [comment]
Do you find anything since you open this issue @sobolevn? I'm running into the same problem.

**Comment by omin** [comment]
Here's a better solution.

Add the following to **app/lib/app/endpoint.ex**
```
plug Plug.Static
  at: "files/", from: "/var/www/app/files/", gzip: false
```

and store the uploaded files at **/var/www/app/files/**

The files will be served at **localhost/files/**

You can learn more at https://hexdocs.pm/plug/Plug.Static.html

Also, using something like nginx to serve the files in production environment may be a better option depending on your requirements.

**Comment by josevalim** [comment]
Excellent solution @omin. Please send a pull request to the guides about adding the Plug.Static configuration if you are storing the files somewhere else.

**Comment by josevalim** [comment]
Actually, I just went ahead and  published some changes: if you have some feedback and more changes, please send a PR: https://github.com/phoenixframework/phoenix_guides/commit/d928b85d8d2a7eba37bcf6845bcdf3fc0012da98 :D Thank you for all the feedback!

**Comment by omin** [comment]
Looks good! Quick question. Do you have a suggestion for generating unique filenames? `Plug.Upload` doesn't seemed to be using anything in the standard. Just thinking that having something like this would be useful https://msdn.microsoft.com/en-us/library/system.io.path.getrandomfilename(v=vs.110).aspx.
