### ISSUE TITLE
Upgrading Guide are not present on the website

### ISSUE THREAD

**Issue by kiaking** [phoenixframework/phoenix_guides#560]
There should be upgrade guide to v1.2 at [News page](http://www.phoenixframework.org/blog) but there isn't.

I would like to help but I have no idea how the website is being generated from this repo. Is there a way for me to contribute on this area?

**Comment by jeregrine** [comment]
@kiaking if you have links to the missing guides I can update this afternoon. Otherwise I can find the links too :-)

**Comment by kiaking** [comment]
@jeregrine Thx.

[This page](http://www.phoenixframework.org/blog) should have link to [this upgrade instruction](https://gist.github.com/chrismccord/29100e16d3990469c47f851e3142f766).

It would be better to have upgrade instruction embed in the former page as same as other upgrade instruction though.

**Comment by jeregrine** [comment]
@kiaking done

**Comment by jeregrine** [comment]
@kiaking Re-embedding, we're PROBABLY going to be moving/changing the guides hosting soonish.

**Comment by kiaking** [comment]
Confirmed. Thank you for the work 👍

**Comment by Valentin-Seehausen** [comment]
Also this site, linked under the _Testing_ Section http://www.phoenixframework.org/docs/channels-1 should point to (my guess) https://github.com/phoenixframework/phoenix_guides/blob/master/testing/J_channels.md

Cool to see such an active community here!
