### ISSUE TITLE
Wrong Testing/Channels link from nav bar

### ISSUE THREAD

**Issue by dzjuck** [phoenixframework/phoenix_guides#572]
Nav bar in [guides](http://www.phoenixframework.org/docs/overview) contains wrong link to Testing/Channels page http://www.phoenixframework.org/docs/channels-1 and it shows Guides/Channels page (http://www.phoenixframework.org/docs/channels), not page about testing. 

I guess, problem rooted in same names of pages.
The repo doesn't contain nav bar generation logic, so i can't try to fix the problem.

**Comment by Gazler** [comment]
Fixed, thanks for the report!
