### ISSUE TITLE
Advanced Deployment Update

### ISSUE THREAD

**Issue by ksolo** [phoenixframework/phoenix_guides#575]
When going through the [Advanced Deployment](http://www.phoenixframework.org/docs/advanced-deployment) Guide it references exrm, which based on the [Github repo](https://github.com/bitwalker/exrm), is being deprecated in favor of Distillery. I would love to help update this guide, however, I have limited experience with deploying Phoenix applications. 

I'll open a PR unless anyone has already started to work on this and would appreciate any feedback.

**Comment by niels** [comment]
Note that distillery itself already contains some documentation around Phoenix deployments: https://hexdocs.pm/distillery/use-with-phoenix.html.

**Comment by eliask** [comment]
I was following the Phoenix guide and hit some problems with exrm with the default settings.
Distillery worked though, so better just not reference exrm in favour of distillery.
