### ISSUE TITLE
Please add a link to THIS repo on the guide pages

### ISSUE THREAD

**Issue by COLABORATI** [phoenixframework/phoenix_guides#581]
Sorry, I posted a few issues to the main phoenix framework issue tracker - but there is a reason for this: on top of every guide page there is a link to the main phoenix repo, but _not_ to this repo.
I would like to suggest to add a link to _this_ repo on every guide page.

**Comment by josevalim** [comment]
We could do like in Elixir guides and have a note at the top or at the end saying contributions are welcome with a link to this repo. :)

**Comment by courajs** [comment]
The link does appear, but only [at the bottom of the overview page](http://www.phoenixframework.org/docs/overview#section-a-note-about-these-guides). I agree it would be better in the footer of every guide page.

**Comment by willykaram** [comment]
@josevalim, further to the suggestion from @courajs,  do you think it would solve the problem if perhaps we included a footer at the bottom of each of the guides? If so, I could work with @courajs in order to create a simple PR that added that footer to the existing guides to implement it.

**Comment by Gazler** [comment]
I think the solution here is to change the overview page a little. This is the first page you see on the guides https://hexdocs.pm/phoenix/1.3.0-rc.2 we can change that page with links to all the relevant Phoenix projects and their repos.

I'm going to close this issue and add it as a task on the guides megathread. Feel free to comment over there. I am happy if you want to work on it @courajs @willykaram.
