### ISSUE TITLE
make the whole guides available on GitHub (including rendering)

### ISSUE THREAD

**Issue by EyMaddis** [phoenixframework/phoenix_guides#585]
This repo only includes the "raw" markdown files, which is nice, but I would like to restyle the actual pages on http://www.phoenixframework.org/docs/.

Especially I would like to do the following:

* add a table of contents for each page
* tweak the css a bit for improved readability (e.g. highlighting headings)
* add syntax highlighting

I think a great example for this are the Ember guides:

rendered: https://guides.emberjs.com/
on GitHub: https://github.com/emberjs/guides

**Comment by EyMaddis** [comment]
I just noticed that this issue might be closable because of https://github.com/phoenixframework/phoenix_guides/issues/391.

**Comment by jeregrine** [comment]
@EyMaddis this is timely because we are working towards doing this now. I will post any updates as we get closer.
