### ISSUE TITLE
ERROR: running mix phoenix.server, failed to connect (invalid_catalog_name): database does not exist

### ISSUE THREAD

**Issue by dansmog** [phoenixframework/phoenix_guides#588]
so i needed to work with a phoenix app api endpoint, following the process cos i had to clone the project.

i followed these steps

    Install dependencies with mix deps.get
    Create and migrate your database with mix ecto.reset
    Start Phoenix endpoint with mix phoenix.server

then i started getting errors of no database and invalid catalog name when i run mix phoenix.server
![screenshot from 2016-09-28 23-15-21](https://cloud.githubusercontent.com/assets/2795724/18934513/0fe9a710-85d2-11e6-9b84-23846b41acc6.png)

**Comment by Gazler** [comment]
The error states that `mix ecto.reset` could not be found.

This was added to the installer in phoenix 1.0.3 - any version prior to this will not have the required alias in the mix.exs file.

Either copy the aliases from this commit https://github.com/phoenixframework/phoenix/commit/502e06b521b014c6423fbd26859c21b2057fb23c to your mix.exs file or run:

    mix do ecto.create, ecto.migrate
