### ISSUE TITLE
Interested in details for using systemd with deploys?

### ISSUE THREAD

**Issue by mfeckie** [phoenixframework/phoenix_guides#606]
The guides as it stands only has an example for using upstart http://www.phoenixframework.org/docs/advanced-deployment#section-making-our-application-public

Upstart is getting less common with Ubuntu and co moving more towards `systemd`.

I've just written a blog post about my experience converting across to systemd http://mfeckie.github.io/Phoenix-In-Production-With-Systemd/

Would you folks be interested in me adapting the examples for the phoenix guides?

**Comment by jeregrine** [comment]
We'll be adding a community guides section to the site soon and we will add it there.
