### ISSUE TITLE
Heroku issue: could not load config config/prod.secret.exs

### ISSUE THREAD

**Issue by jaysoifer** [phoenixframework/phoenix_guides#612]
Hi,

I just followed the Heroku part of the guide step by step, which means:

1. "secret key is loaded from Heroku's environment variables instead of `config/prod.secret.exs`".
2. I've deleted "the following line: `import_config "prod.secret.exs"`" from `config/prod.exs`.

When deploying to Heroku (`git push heroku master`) I'm getting a:
`remote: ** (Mix.Config.LoadError) could not load config config/prod.secret.exs` and can't figure out why.

Just in case this might be helpful, this is my **config/prod.exs**:

```elixir
use Mix.Config

# For production, we configure the host to read the PORT
# from the system environment. Therefore, you will need
# to set PORT=80 before running your server.
#
# You should also configure the url host to something
# meaningful, we use this information when generating URLs.
#
# Finally, we also include the path to a manifest
# containing the digested version of static files. This
# manifest is generated by the mix phoenix.digest task
# which you typically run after static files are built.
config :dotcom, Dotcom.Endpoint,
  http: [port: {:system, "PORT"}],
  url: [scheme: "https", host: "jsdotcom.herokuapp.com", port: 443],
  force_ssl: [rewrite_on: [:x_forwarded_proto]],
  cache_static_manifest: "priv/static/manifest.json",
  secret_key_base: System.get_env("SECRET_KEY_BASE")

# Do not print debug messages in production
config :logger, level: :info

# Configure your database
config :hello_phoenix, HelloPhoenix.Repo,
  adapter: Ecto.Adapters.Postgres,
  url: System.get_env("DATABASE_URL"),
  pool_size: String.to_integer(System.get_env("POOL_SIZE") || "10"),
  ssl: true
```

```bash
✘ jsoifer |10:58:09|  ~/Developer/dotcom: elixir -v
Erlang/OTP 19 [erts-8.1] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.3.4
```

**BuildPacks**:

`heroku buildpacks
=== jsdotcom Buildpack URLs
1. https://github.com/HashNuke/heroku-buildpack-elixir.git
2. https://github.com/gjaldon/heroku-buildpack-phoenix-static.git`

Is anyone else facing this issue?

**Comment by ericmj** [comment]
You probably did some mistake, for example forgetting to commit the file. When asking questions about errors please include the full error so it's easier to help you.

**Comment by jaysoifer** [comment]
You're right, just fixed it.

I am working on a "heroku" local branch and was trying to do a `git push heroku master`.

Switched to `git push heroku heroku:master` and it worked.

Thank you anyway.
