### ISSUE TITLE
Include watcher script for building the docs

### ISSUE THREAD

**Issue by Gazler** [phoenixframework/phoenix_guides#613]
@wsmoak @phoenixframework/phoenix-docs 

I was thinking of adding something like this, to either the README, as a separate shell script, or as a mix task:

```
while true
  do
    inotifywait -r -e modify -e move -e create -e delete docs/ | while read line
      do
        echo "Building docs"
        MIX_ENV=docs mix docs
      done
  done
```

Thoughts?

**Comment by lpil** [comment]
Sounds like a good idea to me.

**Comment by chrismccord** [comment]
@Gazler 👍 and let's wrap it in a mix task `mix docs.watch` ? Also, we can print a helpful based on  System.find_executable
