### ISSUE TITLE
Umbrella Guides (1.3+ and future)?

### ISSUE THREAD

**Issue by ybur-yug** [phoenixframework/phoenix_guides#621]
With the addition on master of `mix phx.new --umbrella`, will this become the new standard for creating applications from the start in the guides?

If this hasn't already been started or addressed, if it is the call to do umbrellas, I'm working on one right now already and though the generators are still being worked on [here](https://github.com/phoenixframework/phoenix/pull/1927), the rest of the main pieces could all be updated and that finished last. It wouldn't be too hard to start putting it together as I go.

Thoughts?

**Comment by Gazler** [comment]
I am not sure if making umbrella applications the default for the guides will introduce additional complexity. It is another thing for people who are new to Elixir to grasp. However I do think that umbrella applications are the correct way to structure things and think we should be pushing people to the correct structure for their applications.

We should at minimum have a section/page on umbrella applications and the benefits. This should be mentioned early on in the guides - when introducing to `mix phx.new` we could at that point mention umbrella applications and their advantages, providing a link to the umbrella section.

The umbrella page for the guides can be written any time, and will be useful regardless of the final choice for the Phoenix generator defaults.
