### ISSUE TITLE
Produce epub version of Guides and API docs

### ISSUE THREAD

**Issue by wsmoak** [phoenixframework/phoenix_guides#623]
Now that the guides are included with the API docs, and ExDoc has epub support, should we configure the build so that both html and epub are produced?

Here's a preview:  http://wsmoak.net/phoenix/Phoenix-v1.3.0-dev.epub  (It's not picking up the page titles of the 'extras' for the table of contents.  Not sure if that's a bug.)

It currently takes two steps:  `mix docs` and then `mix docs -f epub`.  

(I tried combining them with `mix do ...` but was not successful.  There's probably a way.)

(It's also possibly by adding `formatter:  "epub"` to the 'docs' config, but there's only one of those, so it would need to get merged in on the second run somehow.)

The change for this will need to be added to the phoenix `mix.exs` but I thought it was better to discuss here since it's documentation related.

The phoenix mix.exs has `preferred_cli_env: [docs: :docs],` so that you do not have to type `MIX_ENV=docs` every time.

When I tried to define an alias in an attempt to get docs to run twice, it seemed to lose that preferred environment.

Assuming we want to do this, is it possible to configure mix.exs so that both the html and the epub are created with a single command?

**Comment by wsmoak** [comment]
@milmazz if you have time, do you have any insight on why the epub for the phoenix docs doesn't have 'chapter titles' in the table of contents for the 'extras' pages?

This is with `mix docs -f epub` in the phoenixframework/phoenix project, so that it builds both the API docs _and_ the guides together.

It looks like this:

![phoenix-epub-toc](https://cloud.githubusercontent.com/assets/20140/20415125/5909e280-ad04-11e6-9846-90a35b6e25fe.png)

Then if you look at the rendered pages, it's duplicating the page title:

![phoenix-epub-duplicate-header](https://cloud.githubusercontent.com/assets/20140/20415222/e05de59c-ad04-11e6-84f0-29e1381e99b3.png)

I tried it with a newly generated simple project with just README included as an extras page, and could not reproduce it.  (Though in that case I got uppercase README as the 'chapter title' which isn't what I wanted either -- it seems to be picking up the filename.)

Let me know if I should open an issue in ex_doc, I wasn't sure if we've just got it configured wrong.

**Comment by milmazz** [comment]
@wsmoak I already reproduce the error. So, let me find out what is happening here. I'll let you know asap, thanks for the report and for trying this new feature :)

**Comment by milmazz** [comment]
@wsmoak First fix :)

![screen shot 2016-11-17 at 10 25 06 pm](https://cloud.githubusercontent.com/assets/34700/20418585/c9c6b54c-ad14-11e6-9fbc-b266ae63f48d.png)

**Comment by josevalim** [comment]
@milmazz beautiful. Do you think we can use the newly added :group attribute on epub too? It would be nice if the table of contents looked like:

```
## Guides

1. ...
2. ...
35. ...

## Modules

36. ...
51. ...

## Exceptions

...

## Protocols

...
```

But I am not sure if that is possible.

**Comment by wsmoak** [comment]
Thanks @milmazz and @josevalim !  I switched to ex_doc master and updated the ref to the latest phoenix_guides, here is what it looks like now:   http://wsmoak.net/phoenix/Phoenix-v1.3.0-dev.epub 

The two-digit numbers on the first page are cut off a bit on the left.

Speaking of numbers, they were dropped from the left menu in the HTML view on the theory that if people want them, they will put them in the H1's in the markdown content.  Especially if you're able to do the 'groups' in the TOC the numbers may not be necessary.

Can we have a title page with the project name and version? :D

But anyway, back to the original question:  Is there a way to get the build to generate both the HTML and the Epub content in a single command, while preserving the `preferred_cli_env` ?

**Comment by josevalim** [comment]
@wsmoak I have added support for multiple formatters by setting `docs: [formatters: ["html", "epub"]]`.

**Comment by milmazz** [comment]
> Do you think we can use the newly added :group attribute on epub too?

@josevalim Yes, I think that would we nice, I'll work on that.

> The two-digit numbers on the first page are cut off a bit on the left.

@wsmoak What about to center the content on the first page, it will look better? WDYT?

> Speaking of numbers, they were dropped from the left menu in the HTML view on the theory that if people want them, they will put them in the H1's in the markdown content. Especially if you're able to do the 'groups' in the TOC the numbers may not be necessary.

@wsmoak No problem, that's easy to change :)

> Can we have a title page with the project name and version? :D

@wsmoak Right now each title should follow this format:

```eex
<title><%= page.title %> - <%= config.project %> v<%= config.version %></title>
```

**Comment by wsmoak** [comment]
It looks great!  No more numbers, chapter titles are there, and no more duplicate page titles.

@milmazz by 'title page' I meant the very first page of the document.  Right now if you 'page up' all the way to the front of the doc, you are on "Table of contents" and the only place it says Phoenix is in the title bar.

IMO, no, I wouldn't center the items in the TOC.  Left aligned bullets look better I think.

Thank you for the new multiple formatter option @josevalim, that works great as well.

**Comment by milmazz** [comment]
@wsmoak Is there anything left to close this issue? Let me know if I can help.

**Comment by jeregrine** [comment]
@wsmoak @josevalim Where does the Epub version of the guides end up being deployed to? Does Hexdocs support it?

**Comment by josevalim** [comment]
@jeregrine Hex is a static upload so it supports whatever you push to it. :)
