### ISSUE TITLE
Stale link in Routing explanation

### ISSUE THREAD

**Issue by jbodah** [phoenixframework/phoenix_guides#630]
[This page](http://www.phoenixframework.org/v0.7.2/docs/routing#section-the-before-pipeline) references the `:before` pipeline from [the Phoenix router documentation](https://hexdocs.pm/phoenix/Phoenix.Router.html) however the quoted pipeline is not in the router documentation

**Comment by Ch4s3** [comment]
Looks like the old version of the docs page points to the latest version of the hex docs.

**Comment by bryanstearns** [comment]
@jeregrine This seems to have been fixed: the Routing guide no longer mentions a :before pipeline. Close.
