### ISSUE TITLE
Channels guide is a bit ambiguous about the scope of assigns

### ISSUE THREAD

**Issue by scouten** [phoenixframework/phoenix_guides#631]
On the page http://www.phoenixframework.org/docs/channels, the term "channel socket" is used a couple of times but is not well defined. Specifically, the distinction between the overall *connection* and the channel socket is fuzzy.

I was just burned by assuming that a value assigned to a socket via `Phoenix.Socket.assign/3` would be visible when joining another channel. (Spoiler alert: It's not.) I see that there was [an intentional design choice to limit the scope of assigns to a single channel](https://github.com/phoenixframework/phoenix/issues/203), which is fine, but IMHO this is not yet well explained.

Note that I'm specifically not asking you to revisit phoenixframework/phoenix#203, but rather to make the documentation more clear than it currently is about the distinction between "channel socket" and "user socket" (is that even the right term?) and how that affects the behavior of `Phoenix.Socket.assign/3`. Thank you!

**Comment by jeregrine** [comment]
@scouten If you are interested in helping out with this we would very much appreciate the help!
