### ISSUE TITLE
guides are blank

### ISSUE THREAD

**Issue by LTheGreats** [phoenixframework/phoenix_guides#641]
I went to the phoenix website then I selected the guides and I selected getting started, but it was blank. Then I selected a bunch of other guides but they were all blank!

**Comment by ericmj** [comment]
Are you talking about these guides http://www.phoenixframework.org/docs/overview? They are not blank for me, maybe there is some kind of styling issue with your browser?

**Comment by LTheGreats** [comment]
I switched to a different browser and saw that they were not blank so it must have been some sort of styling issue in my browser.
