### ISSUE TITLE
Dockerized Phoenix/Elixir and Postgres Guide

### ISSUE THREAD

**Issue by aphillipo** [phoenixframework/phoenix_guides#642]
Is anyone interested and or working on a full Docker for Dev -> CI -> Production.

I can write this as I have just finished doing it.  With different docker files for each Dev, Test, CI, Prod and a base image that's shared.

You type: 

VERSION=1.1.2 MIX_ENV=dev docker-compose up --build

For example and it'll run the dev server.

Also includes Docker compose and possible deployment strategies (i.e. labelling and constraints of database servers in docker swarm, for example).

Thoughts? Might be a beast and might be better outside the phoenix guides but I'm happy to write it up.

**Comment by Ch4s3** [comment]
That might be nice

**Comment by jeregrine** [comment]
@aphillipo @Ch4s3 If someone were to write a blog post or guide, we will reference it in the future as a community guide.

**Comment by aphillipo** [comment]
Just link to mix_docker maybe: https://github.com/Recruitee/mix_docker
