### ISSUE TITLE
Screenshot is missing

### ISSUE THREAD

**Issue by JunpeiAnzai** [phoenixframework/phoenix_guides#649]
At Adding Pages, Section "A New Template"
http://www.phoenixframework.org/docs/adding-pages#section-a-new-template
![image](https://cloud.githubusercontent.com/assets/2715745/22395544/43d776fc-e585-11e6-8568-29ff6c121ef7.png)

**Comment by phil-r** [comment]
Also last screenshot is wrong.

But in [/docs/adding_pages.md](https://github.com/phoenixframework/phoenix_guides/blob/master/docs/adding_pages.md) everything looks ok.

**Comment by JunpeiAnzai** [comment]
I noticed http://www.phoenixframework.org/docs/ is not up to date(another example: [/docs/testing/testing.md](/phoenixframework/phoenix_guides/blob/master/docs/testing/testing.md) and http://www.phoenixframework.org/docs/introduction )

So, github-side is no problem, it mey be not issue.
