### ISSUE TITLE
Anchors of Section Header is not unique

### ISSUE THREAD

**Issue by JunpeiAnzai** [phoenixframework/phoenix_guides#650]
In [Adding Pages](http://www.phoenixframework.org/docs/adding-pages), there are two section headers pairs named "A New Route" and "A New Template".

These pairs have same link anchors (#section-a-new-route, #section-a-new-template), and always jump to former anchor by clicking.

In case of Github markdown, anchors are generated in order to be unique, but readme.io is maybe not.

**Comment by chrismccord** [comment]
This was a result of the readme hosting, which will be fixed when we moved things over to hexdocs. Thanks!
