### ISSUE TITLE
Broken link in the "Controllers" guide

### ISSUE THREAD

**Issue by Fnux** [phoenixframework/phoenix_guides#651]
In [Setting the Content Type](http://www.phoenixframework.org/docs/controllers#section-setting-the-content-type) : 

> For a list of valid content mime-types, please see the [mime.types](https://github.com/elixir-lang/plug/blob/master/lib/plug/mime.types) documentation from the Plug middleware framework.

=> https://github.com/elixir-lang/plug/blob/master/lib/plug/mime.types returns 404.

**Comment by EduardoBautista** [comment]
Hi @Fnux :)

You can find the current link in the repo, which is more up to the date than the website.  Here is the link in case you still need it:

http://www.phoenixframework.org/docs/controllers#section-setting-the-content-type

**Comment by germsvel** [comment]
Just following the train of thought, I believe Eduardo meant to post this link: 

https://github.com/phoenixframework/phoenix_guides/blob/master/docs/controllers.md#setting-the-content-type

**Comment by EduardoBautista** [comment]
@germsvel Ah sorry!  Yes, that is the correct link.

**Comment by Fnux** [comment]
Thank you! I guess we can close the issue since it's fixed in the repo.

(Can someone update the website... ?)

**Comment by bryanstearns** [comment]
@jeregrine I've verified that the link is correct on master as well as on hex.pm :-)... close please.

**Comment by mitchellhenke** [comment]
@jeregrine / @Gazler this can be closed.  https://hexdocs.pm/phoenix/controllers.html has the correct link now.
