### ISSUE TITLE
broken link in controllers guide

### ISSUE THREAD

**Issue by nhooyr** [phoenixframework/phoenix_guides#658]
http://www.phoenixframework.org/docs/controllers#section-setting-the-content-type

I'm not sure where `mime.types` documentation is now. What should this link be changed to point towards?

**Comment by EduardoBautista** [comment]
Found it for you :)

https://github.com/elixir-lang/mime/blob/master/lib/mime.types

But yeah, the documentation is now out of date and no one seems to be maintaining it.

**Comment by EduardoBautista** [comment]
The docs in this repo is a bit more up to date.

**Comment by nhooyr** [comment]
Thanks!
