### ISSUE TITLE
links to github should include the commit

### ISSUE THREAD

**Issue by nhooyr** [phoenixframework/phoenix_guides#659]
In http://www.phoenixframework.org/docs/controllers#section-setting-the-http-status the link to the status codes is out of sync because it did not link to the commit as well.

**Comment by willykaram** [comment]
@nhooyr thanks for pointing this out. Could you be more precise about which link/text you mean? I took a quick look at the guide, and it appears that though the "mime.types" link is broken and may be pointing to an invalid URL:

   https://github.com/elixir-lang/plug/blob/master/lib/plug/mime.types

I that the link you were referring too.

Would you possibly be able to submit a pull request suggesting a correction, which I could review? This is the guide about how to contribute: 

   https://github.com/phoenixframework/phoenix_guides/blob/master/CONTRIBUTING.md

If you're not able to do that, then perhaps I could create a pull request, and then you could review mine?

Once we get a correct PR in place, I can reach out to @Gazler or @jeregrine to see if the agree with the PR and can merge it.

**Comment by nhooyr** [comment]
@willykaram ctrl+f "friendly names". That is the link. If you scroll down, you will see that it does not outline all of the status codes because it is now out of sync. I could review yours no problem.

**Comment by jeregrine** [comment]
@nhooyr I believe this has been fixed, as "friendly names" links to https://github.com/elixir-plug/plug/blob/v1.3.0/lib/plug/conn/status.ex#L9-L69 and is correct.
