### ISSUE TITLE
why alias the router helpers, isn't that the default?

### ISSUE THREAD

**Issue by nhooyr** [phoenixframework/phoenix_guides#660]
in http://www.phoenixframework.org/docs/controllers#section-redirection it says

```
It's useful to alias the helpers in web/router.ex in order to shorten the expression.
```

By helpers, it is talking about `MyProject.Router.Helpers`. That is already aliased by default in the controllers, what is this statement talking about? And why alias in `router.ex` if we are using it in controllers?

**Comment by Gazler** [comment]
I believe it should say `web.ex`. However I think the statement could be deleted since the alias is generated in web.ex by default.
