### ISSUE TITLE
Version switcher only shows oldest 10 versions

### ISSUE THREAD

**Issue by mbuhot** [phoenixframework/phoenix_guides#669]
The version switcher shows version v0.6.1 through to v0.13.1, but to actually get to relevant versions of the docs, I have to click "View all versions".

Ideally it should show the 10 most recent versions in descending order.

**Comment by nekath** [comment]
Duplication of: 
- https://github.com/phoenixframework/phoenix_guides/issues/591
- https://github.com/phoenixframework/phoenix_guides/issues/663

@mbuhot Dropdown will be removed. All guides and docs will be moved to ex_doc.

For explanation see:
https://github.com/phoenixframework/phoenix/issues/1460#issuecomment-284527888

**Comment by mbuhot** [comment]
👍 sorry for the dup.
