### ISSUE TITLE
Heroku guide deployment missing secret_key_base

### ISSUE THREAD

**Issue by tsubery** [phoenixframework/phoenix_guides#671]
I followed the [heroku deployment guide](http://www.phoenixframework.org/docs/heroku) and didn't my app got similar error like [this](http://stackoverflow.com/questions/43131515/deploy-phoenix-application-in-heroku-but-result-in-application-error/43152038). Seems like something has changed in the buildpack but I don't have enough experience with heroku or their build-packs to debug it.

**Comment by sngeth** [comment]
Apparently this has to do with mix.exs format(thus your development elixir version) and elixir version used by the buildpack from a followup link in your SO post: https://elixirforum.com/t/deploy-phoenix-application-in-heroku-but-result-in-application-error/4394/4

I.e. If you bootstrapped your app with 1.3.x it will have explicit application dependencies listed in the application function in mix.exs and everything will be OK.

If you bootstrap your app with 1.4.x the heroku buildpack _needs_ to be modified to parse a 1.4.x (currently the buildpack defaults to 1.3.4 https://github.com/HashNuke/heroku-buildpack-elixir/blob/master/elixir_buildpack.config) flavored mix.exs where the application dependencies are inferred. The alternative is to "downgrade" your mix.exs and list explicit dependencies which seems kinda sucky.

I can try to do something testing to confirm this and maybe write a PR to improve this gotcha.

**Comment by tsubery** [comment]
Such a small world. Let me know if I want my help solving or testing this.

**Comment by sngeth** [comment]
Whats your mix.exs look like and whats your  mix phoenix.new -v
Phoenix v1.2.1 output?

I think i made of conflated that the error is with Mix and not Phoenix's generated mix.exs file

**Comment by tsubery** [comment]
mix.exs
```Elixir
defmodule Exportant.Mixfile do
  use Mix.Project

  def project do
    [app: :exportant,
     version: "0.0.1",
     elixir: ">= 1.3.4",
     elixirc_paths: elixirc_paths(Mix.env),
     compilers: [:phoenix, :gettext] ++ Mix.compilers,
     build_embedded: Mix.env == :prod,
     start_permanent: Mix.env == :prod,
     aliases: aliases(),
     deps: deps()]
  end

  # Configuration for the OTP application.
  #
  # Type `mix help compile.app` for more information.
  def application do
    [mod: {Exportant, []},
     extra_applications: [:logger]]
  end

  # Specifies which paths to compile per environment.
  defp elixirc_paths(:test), do: ["lib", "test/support"]
  defp elixirc_paths(_),     do: ["lib"]

  # Specifies your project dependencies.
  #
  # Type `mix help deps` for examples and options.
  defp deps do
    [{:phoenix, github: "phoenixframework/phoenix", override: true},
     {:phoenix_pubsub, "~> 1.0"},
     # {:phoenix_ecto, "~> 3.0"},
     # {:postgrex, ">= 0.0.0"},
     {:phoenix_html, "~> 2.6"},
     {:phoenix_live_reload, "~> 1.0", only: :dev},
     {:gettext, "~> 0.11"},
     {:cowboy, "~> 1.0"},
     {:ex_machina, github: "thoughtbot/ex_machina"},
     {:timex, "~> 3.0"},
     {:timex_ecto, "~> 3.0"},
     {:dotenv, github: "tsubery/dotenv_elixir", only: :test},
     {:hackney, "== 1.6.5", override: true}, #failing tests with 1.7.0
     {:httpoison, "~> 0.10.0"},
     {:csv, "~> 1.4.2"},
   ]
  end

  # Aliases are shortcuts or tasks specific to the current project.
  # For example, to create, migrate and run the seeds file at once:
  #
  #     $ mix ecto.setup
  #
  # See the documentation for `Mix` for more info on aliases.
  defp aliases do
    ["ecto.setup": ["ecto.create", "ecto.migrate", "run priv/repo/seeds.exs"],
     "ecto.reset": ["ecto.drop", "ecto.setup"],
     "test": ["ecto.create --quiet", "ecto.migrate", "test"]]
  end
end
```

I have a bunch of elixir/phoenix versions installed so not sure if ```mix phoenix.new -v``` is relevant. If my memory serves me right, I used the one from master about couple of weeks ago.

**Comment by sngeth** [comment]
Ok yeah everything makes sense like i thought.

Since you used master, the generator is now `mix phx.new` which is Phoenix 1.3.x

I just confirmed that master branch generates a Elixir/Mix 1.4 style mix file for phoenix projects and when i do mix phoenix.new (v1.2 archive) it uses a Elixir/Mix 1.3 style with explicit application dependencies.

So you basically have two options:
1st option seems easier imo.

1. modify your mix.exs to have phoenix's explicit dependencies
```elixir
def application do
    [mod: {Acknowledgex, []},
     applications: [:phoenix, :phoenix_pubsub, :phoenix_html, :cowboy, :logger, :gettext,
                    :phoenix_ecto, :postgrex]]
  end
```

2. Fork  buildpack and bump up https://github.com/HashNuke/heroku-buildpack-elixir/blob/master/elixir_buildpack.config elixir version so it uses mix 1.4

You need to modify your heroku project to remove the oldpack and point at your forked build.

**Comment by tsubery** [comment]
I think there was some misunderstanding. My problem has to do with missing SECRET_KEY_BASE in compile environment. When I hardcode it the problem is gone and when I use ```Map.fetch!(System.get_env(), "SECRET_KEY_BASE")``` in config.exs, I get exception because the value is missing.

**Comment by sngeth** [comment]
Cool very interesting. But it is related to Phoenix version at all? I deployed my own app 1.2 app and could not reproduce https://github.com/sngeth/url_shot which uses system env variable for the secret.

**Comment by tsubery** [comment]
That's a good question, is it possible you have environment variables set in the buildpack configuration?
They removed that from the docs recently but you may have followed in it's previous version.

If anyone encounteres the same problem. I opened a [PR](https://github.com/gjaldon/heroku-buildpack-phoenix-static/pull/60) making phoenix build pack behave like elixir buildpack and export all environment variables by default.
