### ISSUE TITLE
Mobile view is not "zoomed in"

### ISSUE THREAD

**Issue by nucleartide** [phoenixframework/phoenix_guides#677]
Hello,

I'm new to Phoenix and I've been reading the Phoenix guides during my commute (which means reading the guides on an iPhone 😄 ). It seems like the guides are missing a `<meta name="viewport">` tag, which makes the mobile view look zoomed out:

![screen shot 2017-05-11 at 10 26 15 pm](https://cloud.githubusercontent.com/assets/914228/25979853/e646831a-3698-11e7-828a-5475699616f1.png)

It seems like adding `<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">` to the `<head>` element makes it more readable, though the sidebar might require some fiddling.

![screen shot 2017-05-11 at 10 27 16 pm](https://cloud.githubusercontent.com/assets/914228/25979894/2e0ce004-3699-11e7-8f08-0ef22a0a1d2b.png)

I'm not really sure how to build and serve the guides locally... but does this sound like something that should be fixed?

**Comment by Gazler** [comment]
Thanks for raising this. The guides are currently hosted at http://readme.io/ however when version 1.3 arrives, we will be switching over to hexdocs for the guides. You can read more about this change at https://github.com/phoenixframework/phoenix_guides/issues/391
