### ISSUE TITLE
Guides overhaul

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix_guides#680]
It's time to pay down my guides debt with a review and overhaul of the guides and much needed TLC. 

cc @Gazler, @willykaram, @jeregrine 

Here's a shortlist to get us 1.3.0 stable ready. I'm marking the ones that I'm claiming, but others are up for grab if folks have bandwidth on refreshing the existing guides:

* [x] Existing* guides in need of a refresh to include new features and latest conventions:
  * [x] [@heatherm] Installation
    * [x] needs to be bumped to 1.3 version requirements
      * [x] Erlang 18
      * [x] Elixir 1.5
    * [x] needs to reference new `phx_new` archive urls
    * [x] needs to use new `phx.new` task
  * [x] Up And Running
    * [x] needs to use new `phx.new`, `phx.server` tasks
    * [x] all example output needs to be updated to new output
  * [x] [CM] Adding Pages
    * [x] needs to discuss new directory structure and update tree listings
    * [x] needs to discuss new assets directory. `web/static` has moved to `assets`. `web/static/assets` has moved to `assets/static`, etc.
    * [x] modules need to use new `Web` namespace
    * [x] `Map.get(assigns, :messenger)` should be `assigns.messenger` since we've long raised on missing assigns
    * [x] __new additions__
      * [x] make small mention of EEx engine escaping by default when talking about templates (explained in detail later in Views guide, but should be mentioned here)
  * [x] [@gazler] Routing
    * [x] web namespace
    * [x] needs to use `phx.routes` with new example output
    * [x] __new additions__
      * [x] cover basic `forward` usecases and usage
  * [x] Plug
    * [x] null-arity calls should use parens
    * [x] web namespace in examples
  * [x] Controllers
    * [x] web namespaces
    * [x] revamp code examples to follow conventions, such as always using parens when piping, no single line pipe.
    * [x] __new additions__
      * [x] discuss `halt` when talking about controller plugs and its importance to prevent invoking the controller action
      * [x] action_fallback
  * [x] Views
    * [x] web namespaces
    * [x] update file path locations
    * [x] output of iex examples need refreshed
    * [x] __new additions__
      * [x] [CM] should show examples of functions on the view being available in eex templates and discuss why
  * [ ] Channels
    * [x] should cross-ref TBD presence guide at the end
    * [x] web namespace
    * [x] file paths
    * [ ] should warn about using `handle_out` with potential N query problems
    * [ ] linked `phoenix_chat_example` desperately needs overhaul to 1.3 and polished
    * [ ] __new additions__
      * [ ] needs to better discuss process-model on server
      * [ ] needs to discuss `handle_info`
      * [ ] Discuss channel security and auth, with examples (we can lift examples from generated socket.js file)
      * [x] should cross-ref Phoenix.Token
      * [ ] bonus points if we can show embedded gifs of examples as we go
  * [x] [CM] Ecto Models (larger revisions required here compared to previous guides)
    * [x] rename to Ecto Schemas
    * [x] heavier focus on the purpose of schemas casting using input
    * [x] use `phx.gen.schema` task
    * [x] __new additions and major revisions__
      * [x] do not discuss relationships in detail, deferring to context guide which will build off this example
      * [x] close guide by discussing wrapping up Ecto repo access and queries into contexts, with TBD cross-ref
  * [x] Testing Guides
    * [x] blocked until context guide is written, which testing guides will build off of
  * [ ] Deployment
    * [ ] review Heroku and update for proper console update
    * [x] update exrm guide to use distillery
  * [x] Bonus Guides
    * ...

*New* guides needed for new features and lacking content:
  * [x] [CM] Presence
  * [ ] [CM]Umbrella applications
  * [x] [CM] Contexts
  * [x] `phx.gen.*` generators, some of these can be grouped into a larger guide, such as a guide on Ecto Schemas
  * [x] Endpoint guide [@gazler] https://github.com/phoenixframework/phoenix_guides/pull/567

Other items to tackle:
  * move guide hosting over to hexdocs. Most of this work is in place, but we need to update the homepage of phoenixframework.org to link back to the hexdocs guides instead of readme hosting.

**Comment by lizvdk** [comment]
I can update _Up And Running._

**Comment by chrisarcand** [comment]
To add: Add more content related to how to how newbies can contribute to the *guides* (not the framework), etc., probably to do after moving to hexdocs.

**Comment by willykaram** [comment]
@chrismccord thanks for making the time for this, I can commit to working on this daily to help move it forward and keep a pulse on things as we progress. Should we start by working through the existing guides, and perhaps limiting our approach to one issue per guide/bullet point you've listed here? That would be 12 issues, and manageable. We could then start to divide them amongst those who are interested in contributing. I know that and @ybur-yug, @dmitrinesterenko and @heatherm has mentioned they may be able to contribute a little to some of the guides.

**Comment by willykaram** [comment]
@lizvdk sounds good, I can work with you on the Up and Running guide revisions, and if you prep draft PR, I can help to review that in order to get it ready for the Phoenix team members to review.

**Comment by willykaram** [comment]
@chrisarcand I think that those sort of revisions would most likely go into this the Contributing page: https://github.com/phoenixframework/phoenix_guides/blob/master/CONTRIBUTING.md

**Comment by Gazler** [comment]
In terms of deployment, we now point to Distillery in https://github.com/phoenixframework/phoenix_guides/blob/master/docs/deployment/deployment.md#introduction-to-deployment - that page may need some updates, but we already link off to distillery as they have a guide https://hexdocs.pm/distillery/use-with-phoenix.html#content

**Comment by heatherm** [comment]
@willykaram happy to help. Which section can I take?

**Comment by chrismccord** [comment]
@heatherm Installation refresh would be a good one to start with. Thanks!

**Comment by chrismccord** [comment]
@Gazler if Distillery has a guide then we can piggy back off that and make sure to include phoenix relevant bits that they may be missing. Given that, we can also kill off the exrm guide.

**Comment by Gazler** [comment]
Based on the feedback in https://github.com/phoenixframework/phoenix_guides/issues/581 I think we need to modify the overview page (https://hexdocs.pm/phoenix/1.3.0-rc.2) to explain the structure of Phoenix and the guides, as well as links to the relevant repositories.

**Comment by HusseinMorsy** [comment]
I updated the template guide for 1.3 in this PR #698 .
But I couldn't find any todos for the template guide in the Issue.
So I'am not sure, if its ok that I have added the PR #698, without an Issue or a ToDos for this guide.

**Comment by bnstrecker** [comment]
A minor tweak note on Controllers Guide, subsection "Overriding Rendering Formats":  Sentence "Let's say that sometimes we need HTML, sometimes we need plain text, and sometimes we need JSON."  It might be better to drop JSON.  After working through the provided text and HTML examples, I attempted JSON and ran into the same problem that jablan hit and described here: (http://stari-blog.radioni.ca/2016/10/02/phoenix-and-json-templates.html).  Alternatively, a mention that the templating engine can be overridden and a link to a description of how to do so for JSON might avoid potential learner confusion.

**Comment by mitchellhenke** [comment]
- [ ] Discuss channel security and auth, with examples (we can lift examples from generated socket.js file)

was done in #801
