### ISSUE TITLE
CSRF Protection in Phoenix and Angular App

### ISSUE THREAD

**Issue by decentname** [phoenixframework/phoenix_guides#692]
I have an Angular App for which i intend to use Phoenix as backend. Phoenix supports CSRF protection by default where the CSRF token is stored to session. This works fine when Phoenix is rendering views, but how do i get access to CSRF token when my front end is built using Angular js.

**Comment by Gazler** [comment]
This question is not relevant for this repository as it does not relate to any of the guides, and is not an idea for a new guide. This question has already been answered on https://stackoverflow.com/questions/44243491/csrf-protection-in-phoenix-and-angular
