### ISSUE TITLE
mention that function plugs must be imported in the router

### ISSUE THREAD

**Issue by nhooyr** [phoenixframework/phoenix_guides#696]
I did not find this mentioned anywhere at all and so I was very confused with the error messages.

**Comment by nhooyr** [comment]
Also, I'm not sure but is this always the case? Do all function plugs have to be imported?

**Comment by Gazler** [comment]
@nhooyr I'm not quite sure what you mean by this. Could you please elaborate on what the issue was, and what the code change required to fix it was?

**Comment by nhooyr** [comment]
In router.ex, I was trying to use a function plug defined in a context module.

I tried stuff like `plug MyModule.myplug` in router.ex but that did not work. I had to add `import MyModule, only: [myplug: 2]` and then change the above to  `plug :myplug`.

This was not clear to me from the documentation.
