### ISSUE TITLE
Gigalixir Deployment Guide?

### ISSUE THREAD

**Issue by jesseshieh** [phoenixframework/phoenix_guides#701]
Hi! I'm interested in writing a deployment guide for https://www.gigalixir.com to go alongside the Heroku and Exrm guides. If I sent over a pull request, do you think it would be accepted[1]? Gigalixir is a platform-as-a-service much like Heroku except it supports clustering, hot upgrades, and remote console/observer.

[1] The [contributing](https://github.com/phoenixframework/phoenix_guides/blob/master/CONTRIBUTING.md) page suggested I ask first before writing a new guide.

**Comment by jesseshieh** [comment]
If there are any other deployment or production related guides that need writing or fixing, let me know and I can help with those too even if they are unrelated to gigalixir. Happy to help!

Also, [this forum post](https://elixirforum.com/t/paas-heroku-otp-ets/684) suggests that it might make sense to add a caveats section to the Heroku deploy guide since some alchemists are surprised to find out that clustering, hot upgrades, etc are not possible. I'm happy to add this also.

**Comment by pmarreck** [comment]
Seconding the adding of the Heroku caveats in an Elixir context (no clustering or hot upgrades, daily restarts which kill any app-side state such as ETS caches) and perhaps suggesting other available alternatives (such as @jesseshieh's Gigalixir, but perhaps others as well)

**Comment by chrismccord** [comment]
:+1: to a caveats section. For the guide itself, a gigalixir guide would be *great* as a blog post, but not something the guides team should handle. As mentioned in other deploy threads, the guides team can't maintain every common deploy scenario, and we include Heroku since questions about how to deploy there come up so frequently. Thanks!

**Comment by jesseshieh** [comment]
Thanks @chrismccord! When I add the caveat section to the Heroku guide, would it be okay if I added a link to gigalixir so people who are concerned about the caveat have an actionable alternative? Since it's just a link, it wouldn't be anything that the guides team would need to maintain. I admit I'm a bit biased, but I really believe that many alchemists would find gigalixir very useful!

**Comment by OvermindDL1** [comment]
Honestly I'd say the Heroku section should be just out-right removed.  It has so many caveats that make it a surprisingly painful environment.

If anything, I'm unsure anything else should be directly included as well.

However, adding links to such setups makes sense to me, perhaps to the Github Phoenix on a specific Wiki page just specifically for such setups like Heroku and Gigalixer and whatever else.
