### ISSUE TITLE
Different parts still refer to Ecto "models"

### ISSUE THREAD

**Issue by michalmuskala** [phoenixframework/phoenix_guides#707]
* introduction overview
* testing models
* mix tasks
* seeding data
* custom primary key
* testing controllers
* file uploads
* channels

**Comment by earthrid** [comment]
Today I raised at the hexpm repository what now appears to be the same issue. I was redirected to this repository. Here is the issue I raised https://github.com/hexpm/hexpm/issues/562 (this is unactionable by hexpm and so has been closed).

@wojtekmach suggested in his reply that "It should probably link to ecto.html" but I am not sure that that would be an appropriate drop-in replacement without further changes to the documentation.

---------------------
The following pages link to the "Ecto Models Guide" but all give a "Page not found" error.

https://hexdocs.pm/phoenix/seeding_data.html
"as described in the Ecto Models Guide"

https://hexdocs.pm/phoenix/testing_models.html
"In the Ecto Models Guide we generated an HTML resource for users."
+
"If this is not the case, please see the section on adding Ecto and Postgrex of the Ecto Models Guide and join us when that’s done."

https://hexdocs.pm/phoenix/file_uploads.html
"In the Ecto Models Guide, we generated an HTML resource for users."

https://hexdocs.pm/phoenix/controllers.html
"We cover how to use Ecto in a Phoenix project in the Ecto Models Guide."

https://hexdocs.pm/phoenix/testing.html
"and the Ecto Models Guide dives into the details on how it all works."

**Comment by mcelaney** [comment]
@jeregrine  I've got a start on this - will send a PR in a bit

**Comment by mcelaney** [comment]
@bryanstearns is going to handle the testing models and testing controllers as part of https://github.com/phoenixframework/phoenix_guides/issues/721.  The rest is ready for review!

**Comment by earthrid** [comment]
@mcelaney Many thanks.
