### ISSUE TITLE
Consider including the --no-html flag for the section covering skeleton installation

### ISSUE THREAD

**Issue by ipatch** [phoenixframework/phoenix_guides#714]
<img width="843" alt="screen shot 2017-07-25 at 5 39 20 pm" src="https://user-images.githubusercontent.com/613805/28596819-58db1a60-7160-11e7-88e4-ee1cad01140b.png">

**Comment by bryanstearns** [comment]
@jeregrine Hey, neat: already done, in 06d3344eef9339b0f30e44dffdadc5a2923c91d3 ... Close!
