### ISSUE TITLE
Links for subheadings, could it be a thing?

### ISSUE THREAD

**Issue by ipatch** [phoenixframework/phoenix_guides#715]
Reading through some of the guides (which so far I've found very impressive) makes me wonder if it would be possible to add links to subheadings?  Not sure if it is a limitation of ExDoc or not, but having links that point directly to a specific heading could be useful.

For example, here is a screen capture of a two subheadings from the current (v1.3.0 RC3) guides that contain two subheadings, but there isn't a way to link to a specific topic / subheading.

<img width="859" alt="screen shot 2017-07-25 at 5 41 29 pm" src="https://user-images.githubusercontent.com/613805/28596965-18446208-7161-11e7-89ec-37dbc323d458.png">

**Comment by OvermindDL1** [comment]
Specifically I've noticed that some counts of `#` in earmark/ex_docs will generate anchors, where other counts do not.  They all should.

**Comment by jeregrine** [comment]
This might be more of an issue with [ex_doc](https://github.com/elixir-lang/ex_doc/issues) if they have it then we have it.
