### ISSUE TITLE
Upgrade testing guide for Phoenix 1.3

### ISSUE THREAD

**Issue by amarandon** [phoenixframework/phoenix_guides#721]
There are still places where the testing guide refers to `phoenix.gen.html` instead of `phx.gen.html`. It also uses the `HelloPhoenix` module name from the old example project.

I'm happy to make a pass on the testing guide and check that everything is consistent with version 1.3.0. I'm creating this issue for reference and to avoid duplicate work.

**Comment by chrismccord** [comment]
Yes, please go ahead with a PR. Thank you!

**Comment by Gazler** [comment]
Closing in favor of https://github.com/phoenixframework/phoenix/pull/2479
