### ISSUE TITLE
FIX ME - not fixed in ecto guide

### ISSUE THREAD

**Issue by jameskraus** [phoenixframework/phoenix_guides#729]
https://hexdocs.pm/phoenix/ecto.html#content

At the bottom of the page:

![image](https://user-images.githubusercontent.com/415057/28880371-db15f37a-7772-11e7-8968-42252e8d4089.png)

**Comment by jameskraus** [comment]
PR: https://github.com/phoenixframework/phoenix_guides/pull/730

**Comment by chrismccord** [comment]
Merged and published to hexdocs. Thanks!
