### ISSUE TITLE
404: Up and Running - assets/images/welcome-to-phoenix.png

### ISSUE THREAD

**Issue by loeschg** [phoenixframework/phoenix_guides#737]
https://hexdocs.pm/phoenix/assets/images/welcome-to-phoenix.png is 404'ing on https://hexdocs.pm/phoenix/up_and_running.html

**Comment by loeschg** [comment]
Images from https://hexdocs.pm/phoenix/adding_pages.html are also 404'ing

**Comment by Gazler** [comment]
I think https://github.com/phoenixframework/phoenix_guides/pull/718 and https://github.com/phoenixframework/phoenix/commit/b60f423a60786cb0097ced8f46592e9ae6d8f6d5 will have fixed this. Just need to redeploy the guides to hexdocs @chrismccord
