### ISSUE TITLE
Links to 3rd party deployment guides

### ISSUE THREAD

**Issue by Gazler** [phoenixframework/phoenix_guides#739]

**Comment by jeregrine** [comment]
I believe we ended on this being part of the blog post/news/community guides section. #792 Closes this

**Comment by willykaram** [comment]
Here's a collection of some recent links relating to deploying Phoenix; I've tried to limit it to posts that specifically reference Phoenix (as opposed to Elixir generally).

I can write up an intro for a post or an external community guide. While the list doesn't need to be exhaustive, I could update it monthly or quarterly to keep a running list for now.

**LINKS**

The ["Deployment" topic on the Elixir Forums](https://elixirforum.com/c/dedicated-sections/deployment) is a good resource for finding guidance on deploying Phoenix.

[Tutorial: Deploying Elixir applications with Docker and Digital Ocean (May 24th, 2017)](https://subvisual.co/blog/posts/137-tutorial-deploying-elixir-applications-with-docker-and-digital-ocean/)

A Complete Guide to Deploying Elixir & Phoenix Applications on Kubernetes (May 2017) [Part 1](https://blog.polyscribe.io/a-complete-guide-to-deploying-elixir-phoenix-applications-on-kubernetes-part-1-setting-up-d88b35b64dcd), [Part 2](https://blog.polyscribe.io/a-complete-guide-to-deploying-elixir-phoenix-applications-on-kubernetes-part-2-docker-and-81e934c3fceb),[Part 3](https://blog.polyscribe.io/a-complete-guide-to-deploying-elixir-phoenix-applications-on-kubernetes-part-3-deploying-to-bd5b1fcbef87), [Part 4](https://blog.polyscribe.io/a-complete-guide-to-deploying-elixir-phoenix-applications-on-kubernetes-part-4-secret-f851d575bdd1),  [Part 5](https://blog.polyscribe.io/a-complete-guide-to-deploying-elixir-phoenix-applications-on-kubernetes-part-5-clustering-6c30fcd35ce1)

[Phoenix Application Deployment with Nanobox (May 2, 2017)](https://hackernoon.com/phoenix-application-deployment-with-nanobox-1d2274f061e5)

[State of the Art in Deploying Elixir/Phoenix Applications (Mar 16, 2017)](https://hackernoon.com/state-of-the-art-in-deploying-elixir-phoenix-applications-fe72a4563cd8)

[Elixir deployments on AWS (Feb 9, 2017)](https://medium.com/mint-digital/elixir-deployments-on-aws-ee787aa02a9d)

[Deploying Phoenix on Ubuntu with Gatling: How To for an automated Phoenix deployment on Digital Ocean (Dec 30, 2016)](https://dennisreimann.de/articles/phoenix-deployment-gatling-ubuntu-digital-ocean.html)

[Elixir Phoenix App deployed into a Load Balanced DigitalOcean setup (Dec 23, 2016)](http://www.akitaonrails.com/2016/12/23/elixir-phoenix-app-deployed-into-a-load-balanced-digitalocean-setup)

[Deploy an Elixir Phoenix Application to the Smallest DigitalOcean Droplet using Dokku (Sep 28 , 2016)](https://glennjon.es/2016/09/28/deploy-an-elixir-phoenix-application-to-the-smallest-digitalocean-droplet-using-dokku.html)

[How to Create a Minimal Phoenix Elixir Server Docker Image That is Less Than 100 MB (Sep 19, 2016)](http://jeremybellows.com/blog/How-to-Create-a-Minimal-Phoenix-Elixir-Server-Docker-Image)

[How to Set up a Distributed Elixir Cluster on Amazon EC2 (Sep 6, 2016)](http://engineering.pivotal.io/post/how-to-set-up-an-elixir-cluster-on-amazon-ec2/)

[How I Built My Own Heroku for Phoenix Apps: Part 1 (August 23, 2016)](https://hashrocket.com/blog/posts/how-i-built-my-own-heroku-for-phoenix-apps-part-1)

[Is Phoenix deployment really that hard? (Aug 2, 2016)](http://cloudless.studio/articles/29-is-phoenix-deployment-really-that-hard)

[Deploying Elixir/Phoenix (July 18, 2016)](https://www.mysteriouspants.com/blog/2016/07/deploying-phoenix/)

[Deploying Elixir to AWS Elastic Beanstalk with Docker (Jul 8, 2016)](https://robots.thoughtbot.com/deploying-elixir-to-aws-elastic-beanstalk-with-docker)

[Deploying a Phoenix application to Dokku(Mar 6, 2016)](https://ashleyconnor.co.uk/2016/03/06/deploying-a-phoenix-application-to-dokku.html)

[Deploying a Phoenix Application Using Ansible-Elixir-Stack (Jul 30, 2015)](https://blog.johanwarlander.com/2015/07/30/deploying-a-phoenix-application-using-ansible-elixir-stack)
