### ISSUE TITLE
Context - In Context Relationships - Missing 'alias' in Example

### ISSUE THREAD

**Issue by dephora** [phoenixframework/phoenix_guides#752]
https://hexdocs.pm/phoenix/contexts.html#in-context-relationships 

In the example above 'We updated the functions to pipe our user changeset into Ecto.Changeset.cast_assoc/2'

`alias Hello.Accounts.User`

should be replaced with 

`alias Hello.Accounts.{User, Credential}`

**Comment by bryanstearns** [comment]
@jeregrine This was fixed already by #722 - close!
