### ISSUE TITLE
Context - FIX MEs

### ISSUE THREAD

**Issue by dephora** [phoenixframework/phoenix_guides#753]
There are several FIX ME links in the Context Guide which need to be fixed now that those sections which they link to are ready.

**Comment by jeregrine** [comment]
I think most of these have been covered, but we'll need someone to go in and verify.

**Comment by bryanstearns** [comment]
@jeregrine Just searched master (case-insensitively) for "fix" - none of the results are FIXMEs, so this can be closed.

**Comment by jeregrine** [comment]
Thank you!! ❤️
