### ISSUE TITLE
Don't recommend generating a skeleton app in the intro

### ISSUE THREAD

**Issue by nisstyre56** [phoenixframework/phoenix_guides#817]
In the guide located at [https://hexdocs.pm/phoenix/installation.html#content](https://hexdocs.pm/phoenix/installation.html#content) it recommends doing `mix phx.new web --no-brunch --no-ecto` which generates an application without brunch to compile static assets (like JS). It does not say why you would want to generate only a skeleton app, so I'm wondering if it might be a good idea to generate a full app instead.

My rationale is that if you follow the guide and get to the point where you want to implement a channel, it seems to assume that you've setup brunch, so either you have to manually setup static asset compilation with brunch, or regenerate your entire app, both of which are frustrating and interrupt the learning process. I think it would be better to recommend just doing `mix phx.new` so that the guide can be followed from start to finish without having to get sidetracked.

**Comment by Gazler** [comment]
Moved to Phoenix Repo.
