### ISSUE TITLE
testing_controllers.md seems out of date

### ISSUE THREAD

**Issue by jmarca** [phoenixframework/phoenix_guides#819]
I was just working through the Testing Controllers guide and it seems to be out of date.  For example, there are mentions of using `mix phoenix.gen.json` and `mix phoenix.gen.model`, which I  *think* are old.

I was working on my own "notes to my future self" for how to stand up a controller, and I could perhaps rewrite the existing guide, but I'm super new to Elixir/Phoenix and would prefer if a more seasoned user would do the rewrite.

**Comment by jmarca** [comment]
Okay, I looked at it more closely and I think I can rewrite it so I'll submit a pull request when done.

**Comment by Gazler** [comment]
Closing in favour of PR.
