### ISSUE TITLE
Testing Guide

### ISSUE THREAD

**Issue by lancehalvorsen** [phoenixframework/phoenix_guides#99]
There have been several questions on the mailing list lately about how to test various parts of a Phoenix application. It would be great to have a guide as a reference.

**Comment by jeregrine** [comment]
Since @josevalim did such a nice job with ConnTest we should be able to tackle this one.

**Comment by josevalim** [comment]
Thank you! Channel test should come this weekend. We also have ModelCase on
v0.12.0z

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Lead Developer*

**Comment by lancehalvorsen** [comment]
:+1: to the delights of ConnTest and ModelCase!

Also, since the generators now provide test files, getting folks up to speed on testing models and controllers will be significantly easier, I think.

Looking forward to having these conveniences on Channels as well.

**Comment by lancehalvorsen** [comment]
I just opened up PR #238 as a skeleton for this.

I'm working on the intro now, and will head into the models and controllers in turn. The larger plan is to use the the HTML resource we built for ecto models as a jumping off place because a) folks should be familiar with the code already, and b) there are already tests in place that we can add on to. :^)

**Comment by gjaldon** [comment]
Would you like some help here, @lancehalvorsen? I've had the chance to use `Phoenix.ChannelTest` when working with the channel generator in Phoenix and have used ConnTest and ModelCase in an app I'm building.

**Comment by lancehalvorsen** [comment]
Yes, please! Thanks so much for the offer, @gjaldon.  :)

**Comment by lancehalvorsen** [comment]
@gjaldon, I just closed this https://github.com/phoenixframework/phoenix_guides/pull/152, but there may still be things you can use from it. @paulcsmith has kindly offered it up if it's useful.

**Comment by paulcsmith** [comment]
@gjaldon LMK if you need any help with the channel guide. As @lancehalvorsen mentioned, the one I started might be a good outline for the new one

**Comment by gjaldon** [comment]
@paulcsmith thanks! Will let you know if I get stuck and will likely use the one you started as outline.

**Comment by jsncmgs1** [comment]
I'm going to start on a guide for Controller specs, specifically testing JSON responses.  I personally never write controller tests if I'm rendering templates (I write feature tests), so if someone else would like to tackle that chunk that would be great.  If not, I'll do it after I'm done with the JSON stuff.

Or perhaps the guide for testing non API controllers is a guide on features tests?

**Comment by jsncmgs1** [comment]
Also, I feel like we should have a task list so we have a goal to work toward for closing this:

- [ ] Controller Tests
- [ ] Feature Tests ??

Given that Models and Channels already have a guide, I feel like once we have these checked off that's the core of what people are generally testing, and other things like Routes, Mailers, can have their own issues.
